<?php
declare(strict_types=1);
requireRole(['owner','admin']);if(!applicationsReady()){echo '<section class="panel"><div class="panel-heading"><div><h2>Public admissions upgrade required</h2><p>Back up, then <a href="upgrade.php">upgrade installed modules</a>. Nothing is published automatically.</p></div></div></section>';return;}
if(isset($_GET['application'])):
$r=staffApplication((int)$_GET['application']);$data=json_decode($r['data_json'],true,512,JSON_THROW_ON_ERROR);$account=one('SELECT * FROM applicant_accounts WHERE id=?',[$r['applicant_id']]);$events=rows('SELECT * FROM application_events WHERE application_id=? ORDER BY id DESC LIMIT 100',[$r['id']]);
?>
<section class="panel"><div class="panel-heading"><div><h2><?=e($r['reference'])?> · <?=e($r['status'])?></h2><p>Version <?=(int)$r['version']?> · <?=e($r['submitted_at'])?></p></div><a href="?page=applications">All applications →</a></div><div class="settings-body"><dl><?php foreach(['name'=>'Applicant','institute_name'=>'Institute at submission','course_name'=>'Course at submission','phone'=>'Phone','city'=>'City','qualification'=>'Qualification','completion_year'=>'Completion year','note'=>'Applicant note'] as $k=>$label):?><dt><strong><?=e($label)?></strong></dt><dd><?=e($data[$k])?></dd><?php endforeach;?></dl><p>Verified email: <?=e($account['email'])?> · Applicant access: <?=$account['active']?'Enabled':'Suspended'?></p><p><strong>Quoted fee: <?=money((int)$r['fee_minor'])?></strong>. Approval uses this application fee snapshot, not a subsequently changed course price. Confirm eligibility, documents, fee terms and any legally required guardian consent offline.</p><details><summary>Privacy notice accepted</summary><p><?=nl2br(e($r['consent_notice']))?></p><small><?=e($r['consent_version'])?></small></details>
<?php if(!in_array($r['status'],['Admitted','Rejected','Withdrawn'],true)):
formStart('application_review');?><input type="hidden" name="application_id" value="<?=(int)$r['id']?>"><input type="hidden" name="version" value="<?=(int)$r['version']?>"><?php selectField('Review decision','status',['Under review'=>'Under review','Changes requested'=>'Request corrections','Rejected'=>'Reject application']);textArea('Message visible to the applicant','message','',true);formEnd('Save review decision');?><hr>
<?php formStart('application_admit');?><input type="hidden" name="application_id" value="<?=(int)$r['id']?>"><input type="hidden" name="version" value="<?=(int)$r['version']?>"><?php textArea('Admission message visible to the applicant','message','',true);?><label><span><input type="checkbox" name="approval" value="yes" required> I have verified eligibility, original documents and required consent, confirmed the quoted fee, and authorize admission today with student portal access.</span></label><p class="form-hint">Creates one admitted enquiry, student, admission PDF/email queue item and enabled student portal account, atomically. No payment is recorded. Do not approve an existing student or shared email.</p><?php formEnd('Approve admission & enable student portal');endif;
if($user['role']==='owner'):formStart('applicant_toggle');?><input type="hidden" name="application_id" value="<?=(int)$r['id']?>"><p class="form-hint">Applicant access is global across institutes and separate from enrolled-student access. Suspension revokes applicant sessions/codes; it does not withdraw applications or disable the student portal.</p><?php formEnd($account['active']?'Suspend applicant sign-in':'Restore applicant sign-in');endif;?></div></section>
<section class="panel"><div class="panel-heading"><h2>Latest 100 review / correction events</h2></div><?php table(['Time / actor','Applicant-visible message','Audit snapshot'],$events,fn($ev)=>[person($ev['actor'],$ev['created_at']),nl2br(e($ev['message'])),'<details><summary>Before / after</summary><pre class="revision-json">'.e(json_encode(json_decode($ev['snapshot_json'],true),JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)).'</pre></details>']);?></section>
<?php return;endif;
if(isset($_GET['listing'])):
$cid=(int)$_GET['listing'];$course=record('courses',$cid);$listing=one('SELECT * FROM admission_listings WHERE id=?',[$cid]);?>
<section class="panel editor"><div class="panel-heading"><div><h2>Public admission listing · <?=e($course['name'])?></h2><p>Closed by default. Opening publishes this course fee/duration, institute name, city, phone and the text below on apply.php. Do not put internal/private notes in this listing.</p></div></div><?php formStart('admission_listing');?><input type="hidden" name="course_id" value="<?=$cid?>"><input type="hidden" name="version" value="<?=(int)($listing['version']??0)?>"><?php textArea('Public course description','description',$listing['description']??'',true);textArea('Eligibility and original documents to verify at the office','eligibility',$listing['eligibility']??'',true);textArea('Institute privacy notice: purpose, office contact, retention and consent process','privacy_notice',$listing['privacy_notice']??'',true);?><div class="form-grid"><?php field('Open from','opens_on',$listing['opens_on']??date('Y-m-d'),'date');field('Close after','closes_on',$listing['closes_on']??date('Y-m-d',strtotime('+30 days')),'date');selectField('Public applications','accepting',['0'=>'Closed / hidden','1'=>'Open within date window'],$listing['accepting']??'0');?></div><p class="form-hint">Inactive courses remain hidden regardless of this setting. Dates use the configured server timezone. Closing a listing does not cancel existing applications or prevent requested corrections.</p><?php formEnd('Save public listing');?></section><?php return;endif;
$pn=min(100000,max(1,(int)($_GET['p']??1)));$offset=($pn-1)*20;$tab=($_GET['tab']??'')==='listings'?'listings':'queue';?>
<section class="panel"><div class="panel-heading"><div><h2>Online admission desk</h2><p>Applicants verify email and submit online. Staff must review and approve. Check this queue regularly; new applications and review changes do not send automatic alerts.</p></div><a class="button secondary" href="apply.php">Open public admissions ↗</a></div><div class="list-toolbar"><a class="button secondary" href="<?=e(url(['tab'=>'queue','p'=>1]))?>">Application queue</a> <a class="button secondary" href="<?=e(url(['tab'=>'listings','p'=>1]))?>">Manage public course listings</a></div>
<?php if($tab==='listings'):
$list=rows('SELECT c.*,l.accepting,l.opens_on,l.closes_on FROM courses c LEFT JOIN admission_listings l ON l.id=c.id WHERE '.($scope?'c.institute_id=?':'1=1').' ORDER BY c.id DESC LIMIT 21 OFFSET '.$offset,$args);$more=count($list)>20;$list=array_slice($list,0,20);
table(['Course','Course active','Listing setting','Dates',''],$list,fn($c)=>[e($c['name']),badge($c['active']?'Active':'Archived'),badge($c['accepting']?'Open in window':'Closed'),e(($c['opens_on']??'—').' → '.($c['closes_on']??'—')),'<a href="?page=applications&listing='.$c['id'].'">Configure public listing →</a>']);
else:
$filter=is_string($_GET['status']??null)?$_GET['status']:'';$valid=['Submitted','Under review','Changes requested','Admitted','Rejected','Withdrawn'];if(!in_array($filter,$valid,true))$filter='';$aw=$scope?'a.institute_id=?':'1=1';$aa=$args;if($filter){$aw.=' AND a.status=?';$aa[]=$filter;}
$list=rows('SELECT a.*,p.email,c.name course_name,i.name institute_name FROM admission_applications a JOIN applicant_accounts p ON p.id=a.applicant_id JOIN courses c ON c.id=a.course_id JOIN institutes i ON i.id=a.institute_id WHERE '.$aw.' ORDER BY a.updated_at DESC,a.id DESC LIMIT 21 OFFSET '.$offset,$aa);$more=count($list)>20;$list=array_slice($list,0,20);?>
<form method="get" class="search-form list-toolbar"><input type="hidden" name="page" value="applications"><input type="hidden" name="institute" value="<?=$scope?>"><?php selectField('Application status','status',[''=>'All states']+array_combine($valid,$valid),$filter,false);?><button class="button secondary">Filter</button></form><?php table(['Reference / email','Course / institute','State','Last update',''],$list,fn($a)=>[person($a['reference'],$a['email']),person($a['course_name'],$a['institute_name']),badge($a['status']),e($a['updated_at']),'<a href="?page=applications&application='.$a['id'].'">Review application →</a>']);endif;?>
<div class="pagination"><span>Page <?=$pn?></span><div><?php if($pn>1):?><a href="<?=e(url(['p'=>$pn-1]))?>">← Previous</a><?php endif;if($more):?><a href="<?=e(url(['p'=>$pn+1]))?>">Next →</a><?php endif;?></div></div></section>
