<?php
declare(strict_types=1);
requireRole(['owner','admin']);if(!applicationsReady()){echo '<section class="panel"><div class="panel-heading"><div><h2>Public admissions upgrade required</h2><p>Back up, then <a href="upgrade.php">upgrade installed modules</a>. Nothing is published automatically.</p></div></div></section>';return;}
if(isset($_GET['application'])):
$r=staffApplication((int)$_GET['application']);$data=json_decode($r['data_json'],true,512,JSON_THROW_ON_ERROR);$account=one('SELECT * FROM applicant_accounts WHERE id=?',[$r['applicant_id']]);$events=rows('SELECT * FROM application_events WHERE application_id=? ORDER BY id DESC LIMIT 100',[$r['id']]);
?>
<section class="panel"><div class="panel-heading"><div><h2><?=e($r['reference'])?> · <?=e($r['status'])?></h2><p>Version <?=(int)$r['version']?> · <?=e($r['submitted_at'])?></p></div><a href="?page=applications">All applications →</a></div><div class="settings-body"><dl><?php foreach(['name'=>'Applicant','institute_name'=>'Institute at submission','course_name'=>'Course at submission','phone'=>'Phone','city'=>'City','qualification'=>'Qualification','completion_year'=>'Completion year','note'=>'Applicant note'] as $k=>$label):?><dt><strong><?=e($label)?></strong></dt><dd><?=e($data[$k])?></dd><?php endforeach;?></dl><p>Verified email: <?=e($account['email'])?> · Applicant access: <?=$account['active']?'Enabled':'Suspended'?></p><p><strong>Quoted fee: <?=money((int)$r['fee_minor'])?></strong>. Approval uses this application fee snapshot, not a subsequently changed course price. Confirm eligibility, documents, fee terms and any legally required guardian consent offline.</p><details><summary>Privacy notice accepted</summary><p><?=nl2br(e($r['consent_notice']))?></p><small><?=e($r['consent_version'])?></small></details>
<?php if(!in_array($r['status'],['Approved','Admitted','Rejected','Withdrawn'],true)):
formStart('request_application_revision');?><input type="hidden" name="application_id" value="<?=(int)$r['id']?>"><input type="hidden" name="version" value="<?=(int)$r['version']?>"><?php textArea('Specific corrections required from applicant','message','',true);formEnd('Request revision');?><hr>
<?php formStart('reject_application');?><input type="hidden" name="application_id" value="<?=(int)$r['id']?>"><input type="hidden" name="version" value="<?=(int)$r['version']?>"><?php textArea('Reason visible to the applicant','message','',true);formEnd('Reject application');?><hr>
<?php formStart('approve_application');?><input type="hidden" name="application_id" value="<?=(int)$r['id']?>"><input type="hidden" name="version" value="<?=(int)$r['version']?>"><label><span><input type="checkbox" name="approval" value="yes" required> I have verified eligibility, original documents and required consent, confirmed the quoted fee, and authorize admission today with student portal access.</span></label><p class="form-hint">Creates the converted enquiry, student, admission PDF/email queue item and enabled student portal account in one transaction.</p><?php formEnd('Approve application & enable student portal');endif;
if($user['role']==='owner'):formStart('applicant_toggle');?><input type="hidden" name="application_id" value="<?=(int)$r['id']?>"><p class="form-hint">Applicant access is global across institutes and separate from enrolled-student access. Suspension revokes applicant sessions/codes; it does not withdraw applications or disable the student portal.</p><?php formEnd($account['active']?'Suspend applicant sign-in':'Restore applicant sign-in');endif;?></div></section>
<?php if(automationReady()):$certs=rows('SELECT c.*,u.name reviewer FROM certificates c LEFT JOIN users u ON u.id=c.reviewed_by WHERE application_id=? ORDER BY id',[$r['id']]);$runs=rows('SELECT * FROM eligibility_runs WHERE application_id=? ORDER BY id DESC LIMIT 20',[$r['id']]);$mails=rows('SELECT * FROM application_mail WHERE application_id=? ORDER BY id DESC LIMIT 20',[$r['id']]);?>
<section class="panel"><div class="panel-heading"><div><h2>Certificate verification</h2><p>Quarantined uploads. Scan before verifying authenticity. Verification may trigger owner-authorized automatic admission.</p></div></div><?php if(!$certs):?><div class="empty"><p>No uploads yet. Ask the applicant to upload from their application page.</p></div><?php else:table(['Upload','Scan / review','Verified evidence','Actions'],$certs,function($c)use($r){
$meta='<strong>'.e($c['original_name']).'</strong><small>'.e($c['mime']).' · '.number_format((int)$c['bytes']/1024,1).' KB · '.e($c['created_at']).'</small>';
$state=badge($c['scan_state']).' '.badge($c['review_state']).($c['reviewer']?'<small>by '.e($c['reviewer']).'</small>':'');
$ev=$c['review_state']==='Verified'?'<small>'.e($c['qualification_code']).' · '.number_format((int)$c['percentage_minor']/100,2).'% · '.e((string)$c['birth_date']).'</small><small>'.e($c['review_note']).'</small>':'<small>'.e($c['review_note']).'</small>';
$act='<a class="text-link" href="?certificate='.(int)$c['id'].'">Download ↓</a>';
if(!in_array($r['status'],['Admitted','Rejected','Withdrawn'],true)){
if($c['scan_state']==='Pending')$act.='<details class="row-details"><summary>Record scan →</summary><form method="post" class="stack">'.csrf().'<input type="hidden" name="action" value="certificate_scan"><input type="hidden" name="certificate_id" value="'.$c['id'].'"><input type="hidden" name="version" value="'.$r['version'].'">'.(in_array(($GLOBALS['config']['certificates']['scanner']??'manual'),['clamav'],true)?'<p>ClamAV daemon scan will run now.</p>':'<label>Scan result<select name="scan_state"><option value="">Select result</option><option value="Clean">Clean</option><option value="Infected">Infected</option></select></label><label>Scan note<textarea name="scan_note" maxlength="500" rows="2"></textarea></label><label><span><input type="checkbox" name="offline_scan" value="yes" required> I scanned this download on an isolated machine with updated antivirus.</span></label>').'<button class="button secondary">Save scan</button></form></details>';
if($c['scan_state']==='Clean'&&$c['review_state']==='Pending')$act.='<details class="row-details"><summary>Verify evidence →</summary><form method="post" class="stack">'.csrf().'<input type="hidden" name="action" value="certificate_review"><input type="hidden" name="certificate_id" value="'.$c['id'].'"><input type="hidden" name="version" value="'.$r['version'].'"><label>Decision<select name="review_state"><option value="">Select decision</option><option value="Verified">Verified</option><option value="Rejected">Rejected</option></select></label><label>Qualification code (for Verified)<input name="qualification_code" maxlength="80"></label><label>Verified percentage (for Verified)<input name="percentage" inputmode="decimal" maxlength="6" placeholder="75.50"></label><label>Verified birth date (for Verified)<input type="date" name="birth_date"></label><label>Review note<textarea name="review_note" maxlength="500" rows="2" required></textarea></label><label><span><input type="checkbox" name="authenticity" value="yes"> I confirmed original authenticity, evidence accuracy, all other requirements and capacity (required for Verified).</span></label><button class="button">Save verification</button></form></details>';
}
return [$meta,$state,$ev,$act];});endif;?></section>
<section class="panel"><div class="panel-heading"><div><h2>Eligibility automation history</h2><p>Owner-authorized policy checks after certificate verification. Manual review remains the default.</p></div></div><?php table(['Time','Policy / app version','Result','Reason'],$runs,fn($v)=>[e($v['created_at']),'Policy v'.(int)$v['policy_version'].' · App v'.(int)$v['application_version'],badge($v['result']),e((string)(json_decode($v['details'],true)['reason']??''))]);?></section>
<section class="panel"><div class="panel-heading"><div><h2>Applicant email alerts</h2><p>Status updates are queued here; the portal remains authoritative. Blocked means recipient changed.</p></div></div><?php table(['Recipient / subject','Status','Attempts / error',''],$mails,function($n){
$act=in_array($n['status'],['failed','blocked','spooled'],true)?'<form method="post">'.csrf().'<input type="hidden" name="action" value="application_mail_retry"><input type="hidden" name="id" value="'.$n['id'].'"><button class="text-button">Requeue</button></form>':'';
return [person($n['recipient'],$n['subject']),badge(ucfirst($n['status'])),(int)$n['attempts'].' / 5<small>'.e($n['last_error']).'</small>',$act];});?></section>
<?php endif;?>
<section class="panel"><div class="panel-heading"><h2>Latest 100 review / correction events</h2></div><?php table(['Time / actor','Applicant-visible message','Audit snapshot'],$events,fn($ev)=>[person($ev['actor'],$ev['created_at']),nl2br(e($ev['message'])),'<details><summary>Before / after</summary><pre class="revision-json">'.e(json_encode(json_decode($ev['snapshot_json'],true),JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)).'</pre></details>']);?></section>
<?php return;endif;
if(isset($_GET['listing'])):
$cid=(int)$_GET['listing'];$course=record('courses',$cid);$listing=one('SELECT * FROM admission_listings WHERE id=?',[$cid]);?>
<section class="panel editor"><div class="panel-heading"><div><h2>Public admission listing · <?=e($course['name'])?></h2><p>Closed by default. Opening publishes this course fee/duration, institute name, city, phone and the text below on apply.php. Do not put internal/private notes in this listing.</p></div></div><?php formStart('admission_listing');?><input type="hidden" name="course_id" value="<?=$cid?>"><input type="hidden" name="version" value="<?=(int)($listing['version']??0)?>"><?php textArea('Public course description','description',$listing['description']??'',true);textArea('Eligibility and original documents to verify at the office','eligibility',$listing['eligibility']??'',true);textArea('Institute privacy notice: purpose, office contact, retention and consent process','privacy_notice',$listing['privacy_notice']??'',true);?><div class="form-grid"><?php field('Open from','opens_on',$listing['opens_on']??date('Y-m-d'),'date');field('Close after','closes_on',$listing['closes_on']??date('Y-m-d',strtotime('+30 days')),'date');selectField('Public applications','accepting',['0'=>'Closed / hidden','1'=>'Open within date window'],$listing['accepting']??'0');?></div><p class="form-hint">Inactive courses remain hidden regardless of this setting. Dates use the configured server timezone. Closing a listing does not cancel existing applications or prevent requested corrections.</p><?php formEnd('Save public listing');?></section><?php return;endif;
if(isset($_GET['policy'])):
$cid=(int)$_GET['policy'];$course=record('courses',$cid);$policy=automationReady()?one('SELECT * FROM eligibility_policies WHERE id=?',[$cid]):null;$ownerName=$policy?one('SELECT name FROM users WHERE id=?',[$policy['authorized_by']]):null;?>
<section class="panel editor"><div class="panel-heading"><div><h2>Eligibility automation · <?=e($course['name'])?></h2><p>Disabled by default. Owner-only. When enabled, Verified + Clean certificates matching these exact rules auto-admit; all other cases stay manual.</p></div><a href="?page=applications&tab=eligibility">All policies →</a></div><?php if($user['role']!=='owner'):?><p class="inline-note">Only the group owner can authorize automatic admission. Current setting: <?=e($policy&&$policy['enabled']?'Enabled':'Disabled')?>.</p><?php else:formStart('eligibility_policy');?><input type="hidden" name="course_id" value="<?=$cid?>"><input type="hidden" name="version" value="<?=(int)($policy['version']??0)?>"><div class="form-grid"><?php selectField('Automatic admission','enabled',['0'=>'Disabled (manual review)','1'=>'Enabled for matching verified evidence'],(string)($policy['enabled']??'0'));field('Required qualification code','qualification_code',$policy['qualification_code']??'');field('Minimum percentage','minimum_percentage',isset($policy['minimum_percentage'])?number_format($policy['minimum_percentage']/100,2,'.',''):'');field('Minimum age','minimum_age',(string)($policy['minimum_age']??''));field('Maximum age','maximum_age',(string)($policy['maximum_age']??''));field('Age cutoff date','cutoff_on',$policy['cutoff_on']??date('Y-m-d'),'date');?></div><?php textArea('Owner authorization note: rules source, document checks and capacity responsibility','description',$policy['description']??'',true);?><p class="inline-note">Authorized by: <?=e($ownerName['name']??'Not yet authorized')?> · Version <?=(int)($policy['version']??0)?>. Changing rules invalidates previously verified evidence until re-verified.</p><label><span><input type="checkbox" name="confirm" value="yes" required> These are the approved course rules. I authorize automatic admission and portal access for matching verified evidence.</span></label><?php formEnd('Save eligibility policy');endif;?></section><?php return;endif;
$pn=min(100000,max(1,(int)($_GET['p']??1)));$offset=($pn-1)*20;$tab=is_string($_GET['tab']??null)?$_GET['tab']:'';if(!in_array($tab,['listings','eligibility','mail'],true))$tab='queue';?>
<section class="panel"><div class="panel-heading"><div><h2>Online admission desk</h2><p>Applicants verify email and submit online. Status updates are queued for email; check this queue regularly as delivery depends on the mail worker.</p></div><a class="button secondary" href="apply.php">Open public admissions ↗</a></div><div class="list-toolbar"><a class="button secondary" href="<?=e(url(['tab'=>'queue','p'=>1]))?>">Application queue</a> <a class="button secondary" href="<?=e(url(['tab'=>'mail','p'=>1]))?>">Email alerts</a></div>
<?php if($tab==='listings'):
$list=rows('SELECT c.*,l.accepting,l.opens_on,l.closes_on FROM courses c LEFT JOIN admission_listings l ON l.id=c.id WHERE '.($scope?'c.institute_id=?':'1=1').' ORDER BY c.id DESC LIMIT 21 OFFSET '.$offset,$args);$more=count($list)>20;$list=array_slice($list,0,20);
table(['Course','Course active','Listing setting','Dates',''],$list,fn($c)=>[e($c['name']),badge($c['active']?'Active':'Archived'),badge($c['accepting']?'Open in window':'Closed'),e(($c['opens_on']??'—').' → '.($c['closes_on']??'—')),'<a href="?page=applications&listing='.$c['id'].'">Configure public listing →</a>']);
elseif($tab==='eligibility'):
if(!automationReady()){echo '<p class="inline-note">Run the automation upgrade first.</p>';}
else{$list=rows('SELECT c.*,p.enabled,p.version policy_version FROM courses c LEFT JOIN eligibility_policies p ON p.id=c.id WHERE '.($scope?'c.institute_id=?':'1=1').' ORDER BY c.id DESC LIMIT 21 OFFSET '.$offset,$args);$more=count($list)>20;$list=array_slice($list,0,20);
table(['Course','Course active','Automation','Policy',''],$list,fn($c)=>[e($c['name']),badge($c['active']?'Active':'Archived'),badge($c['enabled']?'Enabled':'Disabled'),'v'.(int)($c['policy_version']??0),'<a href="?page=applications&policy='.$c['id'].'">Review policy →</a>']);}
elseif($tab==='mail'):
if(!automationReady()){echo '<p class="inline-note">Run the automation upgrade first.</p>';}
else{$mw=$scope?'a.institute_id=?':'1=1';$list=rows('SELECT m.*,a.reference FROM application_mail m JOIN admission_applications a ON a.id=m.application_id WHERE '.$mw.' ORDER BY m.id DESC LIMIT 21 OFFSET '.$offset,$args);$more=count($list)>20;$list=array_slice($list,0,20);
table(['Reference / recipient','Status','Attempts / error',''],$list,function($n){$act=in_array($n['status'],['failed','blocked','spooled'],true)?'<form method="post">'.csrf().'<input type="hidden" name="action" value="application_mail_retry"><input type="hidden" name="id" value="'.$n['id'].'"><button class="text-button">Requeue</button></form>':'';return [person($n['reference'],$n['recipient']),badge(ucfirst($n['status'])),(int)$n['attempts'].' / 5<small>'.e($n['last_error']).'</small>',$act];});}
else:
$filter=is_string($_GET['status']??null)?$_GET['status']:'';$valid=['Draft','Pending Review','Submitted','Under review','Changes requested','Revision','Approved','Admitted','Rejected','Withdrawn'];if(!in_array($filter,$valid,true))$filter='';$aw=$scope?'a.institute_id=?':'1=1';$aa=$args;if($filter){$aw.=' AND a.status=?';$aa[]=$filter;}
$list=rows('SELECT a.*,p.email,c.name course_name,i.name institute_name FROM admission_applications a JOIN applicant_accounts p ON p.id=a.applicant_id JOIN courses c ON c.id=a.course_id JOIN institutes i ON i.id=a.institute_id WHERE '.$aw.' ORDER BY a.updated_at DESC,a.id DESC LIMIT 21 OFFSET '.$offset,$aa);$more=count($list)>20;$list=array_slice($list,0,20);?>
<form method="get" class="search-form list-toolbar"><input type="hidden" name="page" value="applications"><input type="hidden" name="institute" value="<?=$scope?>"><?php selectField('Application status','status',[''=>'All states']+array_combine($valid,$valid),$filter,false);?><button class="button secondary">Filter</button></form><?php table(['Reference / email','Course / institute','State','Last update',''],$list,fn($a)=>[person($a['reference'],$a['email']),person($a['course_name'],$a['institute_name']),badge($a['status']),e($a['updated_at']),'<a href="?page=applications&application='.$a['id'].'">Review application →</a>']);endif;?>
<div class="pagination"><span>Page <?=$pn?></span><div><?php if($pn>1):?><a href="<?=e(url(['p'=>$pn-1]))?>">← Previous</a><?php endif;if($more):?><a href="<?=e(url(['p'=>$pn+1]))?>">Next →</a><?php endif;?></div></div></section>
