<?php
declare(strict_types=1);
function apForm(string $action): string{return '<form method="post">'.csrf().'<input type="hidden" name="action" value="'.e($action).'">';}
function apUploadForm(string $action): string{return '<form method="post" enctype="multipart/form-data">'.csrf().'<input type="hidden" name="action" value="'.e($action).'">';}
function apField(string $label,string $name,string $value='',int $max=200,string $type='text'): void {if(isset($_POST[$name])&&is_string($_POST[$name]))$value=$_POST[$name];echo '<label>'.e($label).'<input name="'.e($name).'" type="'.$type.'" maxlength="'.$max.'" value="'.e($value).'" required></label>';}
function applicationFormFields(array $data,string $privacy): void {
    foreach([['Full legal name','name',120],['Contact phone','phone',30],['City / town','city',100],['Highest completed qualification','qualification',300],['Completion year','completion_year',4]] as [$label,$key,$max])apField($label,$key,(string)($data[$key]??''),$max);
    $note=is_string($_POST['note']??null)?$_POST['note']:($data['note']??'');echo '<label>Additional information (optional; no identity numbers or medical information)<textarea name="note" maxlength="1500" rows="4">'.e($note).'</textarea></label><details open><summary>Institute application privacy notice</summary><p>'.nl2br(e($privacy)).'</p></details><label class="ap-check"><input type="checkbox" name="consent" value="yes" required> I have read the notice and consent to processing this application. The details are accurate, and I understand admission requires eligibility verification and office approval. I will contact the office about any required guardian consent.</label>';
}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admissions & applications · Northstar</title><link rel="stylesheet" href="assets/student.css"><link rel="stylesheet" href="assets/admissions.css"><link rel="stylesheet" href="assets/theme.css"><script src="assets/theme.js" defer></script></head><body>
<header class="sp-top"><a class="sp-brand" href="apply.php"><span>N</span> northstar<span class="sp-dot">.</span></a><div class="sp-top-right"><button class="theme-toggle" data-theme-toggle type="button" aria-label="Toggle dark mode" title="Toggle dark mode"><span aria-hidden="true">🌙</span></button><?php if($actor):?><?=apForm('logout')?><button class="sp-text-button">Sign out</button></form><?php else:?><a href="apply.php?page=login">Applicant sign-in ↗</a><?php endif;?><a href="student.php">Enrolled student portal ↗</a></div></header>
<div class="sp-workspace"><nav class="sp-nav" aria-label="Admissions navigation"><a href="apply.php" <?=$page==='courses'?'aria-current="page"':''?>>Courses & institutes</a><a href="apply.php?page=dashboard" <?=in_array($page,['dashboard','application'],true)?'aria-current="page"':''?>>My applications</a><a href="apply.php?page=help" <?=$page==='help'?'aria-current="page"':''?>>How to apply</a></nav><main class="sp-content">
<?php if($error):?><div class="sp-alert error" role="alert"><?=e($error)?></div><?php endif;if($flash):?><div class="sp-alert" role="status"><?=e($flash)?></div><?php endif;?>
<?php if($page==='courses'):
$pn=min(100000,max(1,(int)($_GET['p']??1)));$list=publicCourses(($pn-1)*20);$more=count($list)>20;$list=array_slice($list,0,20);?>
<section class="sp-welcome"><div><span class="sp-eyebrow">YOUR NEXT CHAPTER STARTS HERE</span><h1>Find your course.<br>Start your application.</h1><p>Explore open admissions, verify your email, and follow your application from submission to the office decision.</p><a href="apply.php?page=help">See how admission works →</a></div><span class="sp-star" aria-hidden="true">✦</span></section>
<p class="sp-footnote">Only courses explicitly opened by the institute are shown. Applying does not guarantee a seat. No payment is collected here.</p>
<?php if(!$list):?><section class="sp-card"><h2>No courses currently accepting applications</h2><p>Please contact your institute. Existing applicants can still sign in to check their application.</p></section><?php endif;?><div class="ap-grid"><?php foreach($list as $c):?><article class="sp-card"><div class="sp-eyebrow"><?=e($c['institute_name'])?></div><h2><?=e($c['name'])?></h2><p><?=e($c['duration'])?> · <?=e($c['city'])?></p><p>Listed course fee: <strong>₹<?=number_format((int)$c['fee_minor']/100,2)?></strong></p><p class="sp-small">Apply through <?=e($c['closes_on'])?> · Eligibility is reviewed by the office.</p><a class="sp-link" href="apply.php?page=course&course=<?=(int)$c['id']?>">Course details & apply →</a></article><?php endforeach;?></div><div class="sp-pagination"><span>Page <?=$pn?></span><div><?php if($pn>1):?><a href="apply.php?p=<?=$pn-1?>">← Previous</a><?php endif;if($more):?><a href="apply.php?p=<?=$pn+1?>">Next →</a><?php endif;?></div></div>
<?php elseif($page==='course'):?>
<section class="sp-card"><div class="sp-eyebrow"><?=e($course['institute_name'])?></div><h1><?=e($course['name'])?></h1><p><?=e($course['duration'])?> · <?=e($course['kind'])?> · <?=e($course['city'])?></p><h2>About the course</h2><p><?=nl2br(e($course['description']))?></p><h2>Eligibility</h2><p><?=nl2br(e($course['eligibility']))?></p><h2>Fee and application window</h2><p>Listed fee ₹<?=number_format((int)$course['fee_minor']/100,2)?> · <?=e($course['opens_on'])?> → <?=e($course['closes_on'])?></p><p>Seats, eligibility, document verification and any additional charges must be confirmed with the office. No payment is collected on this page.</p><a class="sp-button" href="apply.php?page=apply&course=<?=(int)$course['id']?>"><?=$actor?'Apply for this course':'Verify email, then apply'?> →</a><h2>Contact the institute</h2><p><?=e($course['institute_name'])?> · <?=e($course['city'])?><br><?=e($course['phone'])?></p><details><summary>Application privacy notice</summary><p><?=nl2br(e($course['privacy_notice']))?></p></details></section>
<?php elseif($page==='login'):?>
<section class="sp-card ap-form"><div class="sp-eyebrow">NEW AND RETURNING APPLICANTS</div><h1>Verify your email</h1><p>Use your own accessible email. A new applicant account is created only after verification. This login is separate from the enrolled-student and staff portals.</p><?php if(($config['environment']??'')==='local'&&($config['mail']['transport']??'')==='log'):?><div class="sp-alert">Local test mode: no real email is sent. Codes are captured privately by the server operator.</div><?php endif;?>
<?php if(isset($_SESSION['applicant_pending'])):?><?=apForm('verify_code')?><label>Six-digit applicant code<input name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" autocomplete="one-time-code" required></label><button class="sp-button">Verify & continue →</button></form><p class="sp-small">Use the latest code in the same browser within five minutes.</p><?php endif;?>
<?=apForm('request_code')?><?php apField('Your email address','email','',200,'email');?><div class="ap-trap" aria-hidden="true"><label>Leave this blank<input name="website" tabindex="-1" autocomplete="off"></label></div><button class="sp-button">Send email code →</button></form><p class="sp-small">Wait 60 seconds before resending. Never share your code. After verification, choose a course from the catalogue.</p></section>
<?php elseif($page==='apply'):
$_SESSION['application_nonce']??=bin2hex(random_bytes(24));?>
<section class="sp-card ap-form"><div class="sp-eyebrow">APPLICATION FORM</div><h1><?=e($course['name'])?></h1><p><?=e($course['institute_name'])?> · Verified email: <?=e($actor['email'])?></p><p>Quoted course fee at submission: ₹<?=number_format((int)$course['fee_minor']/100,2)?>. The office must confirm this fee when approving admission.</p><?=apForm('submit_application')?><input type="hidden" name="course_id" value="<?=(int)$course['id']?>"><input type="hidden" name="request_key" value="<?=e($_SESSION['application_nonce'])?>"><input type="hidden" name="offer_token" value="<?=e(hash('sha256',json_encode($course,JSON_THROW_ON_ERROR)))?>"><div class="ap-trap" aria-hidden="true"><label>Leave blank<input name="website" tabindex="-1" autocomplete="off"></label></div><?php applicationFormFields([],$course['privacy_notice']);?><button class="sp-button">Submit application for review →</button></form><p class="sp-small">After submitting, upload certificates from your application page when the institute enables uploads. No payment is collected here; enrolled students pay separately after admission. Please submit only one active application.</p></section>
<?php elseif($page==='dashboard'):
$pn=min(100000,max(1,(int)($_GET['p']??1)));$list=rows('SELECT * FROM admission_applications WHERE applicant_id=? ORDER BY id DESC LIMIT 21 OFFSET '.(($pn-1)*20),[$actor['id']]);$more=count($list)>20;$list=array_slice($list,0,20);?>
<div class="sp-heading"><div><div class="sp-eyebrow">APPLICANT WORKSPACE</div><h1>My applications</h1><p><?=e($actor['email'])?></p></div><a class="sp-link" href="apply.php">Browse open courses →</a></div><?php if(!$list):?><section class="sp-card"><h2>Your email is verified</h2><p>Choose a course from the catalogue to start your application.</p></section><?php endif;foreach($list as $a):$d=json_decode($a['data_json'],true);?><article class="sp-card sp-notice"><div class="sp-eyebrow"><?=e($a['reference'])?></div><h2><?=e($d['course_name'])?></h2><p><?=e($d['institute_name'])?> · <strong><?=e($a['status'])?></strong></p><p class="sp-small">Submitted <?=e($a['submitted_at'])?></p><a href="apply.php?page=application&id=<?=(int)$a['id']?>">View application, decision & next steps →</a></article><?php endforeach;?><div class="sp-pagination"><span>Page <?=$pn?></span><div><?php if($pn>1):?><a href="apply.php?page=dashboard&p=<?=$pn-1?>">← Previous</a><?php endif;if($more):?><a href="apply.php?page=dashboard&p=<?=$pn+1?>">Next →</a><?php endif;?></div></div>
<?php elseif($page==='application'):$a=$application;$d=json_decode($a['data_json'],true,512,JSON_THROW_ON_ERROR);$events=rows('SELECT actor,message,created_at FROM application_events WHERE application_id=? ORDER BY id DESC LIMIT 100',[$a['id']]);?>
<section class="sp-card"><div class="sp-eyebrow">APPLICATION ACKNOWLEDGEMENT</div><h1><?=e($a['reference'])?></h1><p><strong><?=e($a['status'])?></strong> · Submitted <?=e($a['submitted_at'])?></p><dl><?php foreach(['name'=>'Applicant','institute_name'=>'Institute','course_name'=>'Course','duration'=>'Duration','phone'=>'Phone','city'=>'City','qualification'=>'Qualification','completion_year'=>'Completed in','note'=>'Additional information'] as $key=>$label):?><div><dt><?=e($label)?></dt><dd><?=e($d[$key])?></dd></div><?php endforeach;?><div><dt>Verified email</dt><dd><?=e($actor['email'])?></dd></div><div><dt>Fee quoted on submission</dt><dd>₹<?=number_format((int)$a['fee_minor']/100,2)?></dd></div></dl><p class="sp-small">You may print this page using your browser. This acknowledgement is not a payment receipt or an admission guarantee.</p>
<?php if($a['status']==='Admitted'):?><div class="sp-alert"><strong>Your admission has been approved.</strong> Student portal access was enabled at approval. If access is later disabled, contact the office. Sign in separately with your verified email to see your admission letter, fees and other records. The admission-letter email is queued and depends on the institute's notification worker.</div><a class="sp-button" href="student.php">Open my student portal →</a><?php elseif($a['status']==='Rejected'):?><p>Read the office decision below. Contact the institute if you need clarification. This application cannot be edited or reopened.</p><?php elseif($a['status']==='Withdrawn'):?><p>You withdrew this application. You may browse courses and submit a new application if eligible.</p><?php else:?><p>The institute must review your eligibility and documents. Check here for the authoritative status; updates are also queued for email, but delivery depends on the institute mail worker.</p><?php endif;?><details><summary>Privacy notice accepted with this application</summary><p><?=nl2br(e($a['consent_notice']))?></p><small><?=e($a['consent_version'])?></small></details></section>
<?php if(function_exists('automationReady')&&automationReady()):$certs=rows('SELECT id,original_name,mime,bytes,scan_state,review_state,created_at FROM certificates WHERE application_id=? ORDER BY id',[$a['id']]);?>
<section class="sp-card"><h2>Certificate uploads</h2><p class="sp-small">PDF, JPEG or PNG up to 5 MB each, maximum five. Uploads are quarantined until the office scans and verifies them. Do not upload government ID numbers or medical records unless the office explicitly asks.</p><?php if(!$certs):?><p class="sp-small">No certificates uploaded yet.</p><?php else:?><div class="sp-table-wrap"><table><thead><tr><th>File</th><th>Uploaded</th><th>Scan</th><th>Office review</th><th></th></tr></thead><tbody><?php foreach($certs as $c):?><tr><td><?=e($c['original_name'])?><small><?=e($c['mime'])?> · <?=number_format((int)$c['bytes']/1024,1)?> KB</small></td><td><?=e($c['created_at'])?></td><td><?=e($c['scan_state'])?></td><td><?=e($c['review_state'])?></td><td><a href="apply.php?certificate=<?=(int)$c['id']?>">Download ↓</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<?php if(!in_array($a['status'],['Admitted','Rejected','Withdrawn'],true)&&count($certs)<5):?><?=apUploadForm('upload_certificate')?><input type="hidden" name="application_id" value="<?=(int)$a['id']?>"><input type="hidden" name="version" value="<?=(int)$a['version']?>"><label>Choose certificate<input type="file" name="certificate" accept=".pdf,.jpg,.jpeg,.png" required></label><button class="sp-button">Upload for office verification →</button></form><?php elseif(count($certs)>=5):?><p class="sp-small">Upload limit reached. Contact the office for help.</p><?php endif;?></section><?php endif;?>
<?php if($a['status']==='Changes requested'):?><section class="sp-card sp-notice"><h2>Correct and resubmit</h2><p>Read the office's requested changes below. Email, institute, course and quoted fee cannot be changed here.</p><?=apForm('revise_application')?><input type="hidden" name="application_id" value="<?=(int)$a['id']?>"><input type="hidden" name="version" value="<?=(int)$a['version']?>"><?php applicationFormFields($d,$a['consent_notice']);?><button class="sp-button">Resubmit corrected application →</button></form></section><?php endif;?>
<section class="sp-card sp-notice"><h2>Latest 100 application updates</h2><?php foreach($events as $ev):?><article class="sp-support-message"><strong><?=e($ev['actor'])?></strong><p class="sp-small"><?=e($ev['created_at'])?></p><p><?=nl2br(e($ev['message']))?></p></article><?php endforeach;?></section>
<?php if(!in_array($a['status'],['Admitted','Rejected','Withdrawn'],true)):?><section class="sp-card"><details><summary>Withdraw this application</summary><?=apForm('withdraw_application')?><input type="hidden" name="application_id" value="<?=(int)$a['id']?>"><input type="hidden" name="version" value="<?=(int)$a['version']?>"><?php apField('Reason for withdrawal','reason','',500);?><p>Withdrawal closes this application. It does not cancel an already approved admission or refund a payment.</p><button class="sp-button">Confirm withdrawal</button></form></details></section><?php endif;?>
<?php elseif($page==='help'):?>
<section class="sp-card"><h1>Your admission journey</h1><ol><li>Browse a course opened by your institute. Read eligibility, fee information and its privacy notice.</li><li>Verify your own email with a one-time code.</li><li>Submit accurate contact and qualification details. Keep your application reference.</li><li>Upload certificates from your application page when enabled. Uploads are quarantined until scanned and verified.</li><li>Return to My applications to track review and respond to correction requests. Status updates are queued for email, but this page is authoritative.</li><li>The office verifies eligibility and original documents before approving or rejecting admission. Some courses use owner-authorized automatic checks after certificate verification.</li><li>After approval, sign in to the enrolled-student portal for your admission letter, payments, installments, attendance, published results, notices and support.</li></ol><h2>Before you apply</h2><p>There is no guaranteed seat. Payments are collected only after admission through the enrolled-student portal, never on this application page. Contact the institute using the phone on its course page. Do not send government ID numbers, medical records, card details, passwords or OTPs in application notes.</p><h2>Already enrolled?</h2><p><a href="student.php">Use the student portal</a>. If access is disabled or your email is incorrect, contact the office. Applying again does not repair an existing student account.</p><h2>Email and privacy</h2><p>Use a personal email you control, not a shared family address. One active application per applicant is supported. An email cannot be used to create multiple student portal enrolments. Minors should contact the office about its guardian-consent process. Check the institute notice for privacy and retention information.</p></section>
<?php elseif($page==='unavailable'):?><section class="sp-card"><h1>Online admissions are not ready</h1><p>The institute must complete its upgrade or resolve a server issue. Please contact the office.</p></section>
<?php else:?><section class="sp-card"><h1>Page or application unavailable</h1><p>This record is not accessible, or the course is no longer accepting new applications.</p><a href="apply.php">Return to open courses →</a></section><?php endif;?>
<p class="sp-footnote">Northstar admissions · <a href="apply.php?page=help">Application help</a> · <a href="student.php">Student portal</a> · <a href="index.php">Staff sign-in</a></p></main></div></body></html>
