<?php
declare(strict_types=1);
require_once __DIR__.'/site-chrome.php';
require_once __DIR__.'/admission-form.php';
function apForm(string $action): string{return '<form method="post">'.csrf().'<input type="hidden" name="action" value="'.e($action).'">';}
function apUploadForm(string $action): string{return '<form method="post" enctype="multipart/form-data">'.csrf().'<input type="hidden" name="action" value="'.e($action).'">';}
[$apBrand,$apKind,$apCity,$apAddr,$apPhone]=siteBrand();
$apButtons=siteToggle();
if($actor) {$apButtons.=siteProfileBox(['name'=>$actor['email'],'role'=>'Applicant','url'=>'apply.php?page=dashboard']).apForm('logout').'<button class="u-btn ghost" type="submit">Sign out</button></form>';}
else $apButtons.='<a class="u-btn ghost" href="index.php?page=login&show=applicant">Track application ↗</a>';
$apButtons.='<a class="u-btn ghost" href="student.php">Enrolled student portal ↗</a>';
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admissions & applications · Northstar</title><link rel="stylesheet" href="assets/university.css"><link rel="stylesheet" href="assets/theme.css"><link rel="stylesheet" href="assets/portal-theme.css?v=site-theme-v2"><script src="assets/theme.js" defer></script><script src="assets/wizard.js" defer></script></head><body class="portal-surface">
<?=siteHeader($apBrand,$apKind,'',$apButtons)?>
<main class="u-page"><nav class="u-tabs" aria-label="Admissions navigation"><a href="apply.php" <?=$page==='courses'?'aria-current="page"':''?>>Courses & institutes</a><a href="apply.php?page=dashboard" <?=in_array($page,['dashboard','application'],true)?'aria-current="page"':''?>>My applications</a><a href="apply.php?page=help" <?=$page==='help'?'aria-current="page"':''?>>How to apply</a></nav>
<?php if($error):?><div class="u-alert error" role="alert"><?=e($error)?></div><?php endif;if($flash):?><div class="u-alert" role="status"><?=e($flash)?></div><?php endif;?>
<?php if($page==='courses'):
$pn=min(100000,max(1,(int)($_GET['p']??1)));$list=publicCourses(($pn-1)*20);$more=count($list)>20;$list=array_slice($list,0,20);?>
<div class="u-page-head"><div class="u-eyebrow">YOUR NEXT CHAPTER STARTS HERE</div><h1>Find your course. Start your application.</h1><p>Explore open admissions, verify your email, and follow your application from submission to the office decision. <a href="apply.php?page=help">See how admission works →</a></p></div>
<p class="u-small">Only courses explicitly opened by the institute are shown. Applying does not guarantee a seat. No payment is collected here.</p>
<?php if(!$list):?><section class="u-card"><h2>No courses currently accepting applications</h2><p>Please contact your institute. Existing applicants can still sign in to check their application.</p></section><?php endif;?><div class="u-grid"><?php foreach($list as $c):?><article class="u-card"><div class="u-eyebrow"><?=e($c['institute_name'])?></div><h2><?=e($c['name'])?></h2><p><?=e($c['duration'])?> · <?=e($c['city'])?></p><p>Listed course fee: <strong>₹<?=number_format((int)$c['fee_minor']/100,2)?></strong></p><p class="u-small">Apply through <?=e($c['closes_on'])?> · Eligibility is reviewed by the office.</p><a href="apply.php?page=course&course=<?=(int)$c['id']?>">Course details &amp; apply →</a></article><?php endforeach;?></div><div class="u-pagination"><span>Page <?=$pn?></span><div><?php if($pn>1):?><a href="apply.php?p=<?=$pn-1?>">← Previous</a><?php endif;if($more):?><a href="apply.php?p=<?=$pn+1?>">Next →</a><?php endif;?></div></div>
<?php elseif($page==='course'):?>
<section class="u-card"><div class="u-eyebrow"><?=e($course['institute_name'])?></div><h1><?=e($course['name'])?></h1><p><?=e($course['duration'])?> · <?=e($course['kind'])?> · <?=e($course['city'])?></p><h2>About the course</h2><p><?=nl2br(e($course['description']))?></p><h2>Eligibility</h2><p><?=nl2br(e($course['eligibility']))?></p><h2>Fee and application window</h2><p>Listed fee ₹<?=number_format((int)$course['fee_minor']/100,2)?> · <?=e($course['opens_on'])?> → <?=e($course['closes_on'])?></p><p>Seats, eligibility, document verification and any additional charges must be confirmed with the office. No payment is collected on this page.</p><a class="u-btn solid" href="apply.php?page=apply&course=<?=(int)$course['id']?>"><?=$actor?'Apply for this course':'Verify email, then apply'?> →</a><h2>Contact the institute</h2><p><?=e($course['institute_name'])?> · <?=e($course['city'])?><br><?=e($course['phone'])?></p><details><summary>Application privacy notice</summary><p><?=nl2br(e($course['privacy_notice']))?></p></details></section>
<?php elseif($page==='apply'):
$_SESSION['application_nonce']??=bin2hex(random_bytes(24));?>
<section class="u-card"><div class="u-eyebrow">APPLICATION FORM</div><h1><?=e($course['name'])?></h1><p><?=e($course['institute_name'])?> · Verified email: <?=e($actor['email'])?></p><p>Quoted course fee at submission: ₹<?=number_format((int)$course['fee_minor']/100,2)?>. The office must confirm this fee when approving admission.</p><?=apUploadForm('submit_application')?><div class="u-form"><input type="hidden" name="course_id" value="<?=(int)$course['id']?>"><input type="hidden" name="request_key" value="<?=e($_SESSION['application_nonce'])?>"><input type="hidden" name="offer_token" value="<?=e(hash('sha256',json_encode($course,JSON_THROW_ON_ERROR)))?>"><div class="u-trap" aria-hidden="true"><label>Leave blank<input name="website" tabindex="-1" autocomplete="off"></label></div><?php applicationFormFields([],$course['privacy_notice']);?></div></form><p class="u-small">Complete all four steps — personal details, academic details, documents, then preview and submit. Saving a draft keeps your typed details and any attached documents. No payment is collected here; enrolled students pay separately after admission. Please submit only one active application.</p></section>
<?php elseif($page==='dashboard'):
$pn=min(100000,max(1,(int)($_GET['p']??1)));$list=rows('SELECT * FROM admission_applications WHERE applicant_id=? ORDER BY id DESC LIMIT 21 OFFSET '.(($pn-1)*20),[$actor['id']]);$more=count($list)>20;$list=array_slice($list,0,20);?>
<div class="u-page-head"><div class="u-eyebrow">APPLICANT WORKSPACE</div><h1>My applications</h1><p><?=e($actor['email'])?> · <a href="apply.php">Browse open courses →</a></p></div><?php if(!$list):?><section class="u-card"><h2>Your email is verified</h2><p>Choose a course from the catalogue to start your application.</p></section><?php endif;foreach($list as $a):$d=json_decode($a['data_json'],true);?><article class="u-card"><div class="u-eyebrow"><?=e($a['reference'])?></div><h2><?=e($d['course_name'])?></h2><p><?=e($d['institute_name'])?> · <strong><?=e($a['status'])?></strong></p><p class="u-small">Submitted <?=e($a['submitted_at'])?></p><a href="apply.php?page=application&id=<?=(int)$a['id']?>">View application, decision &amp; next steps →</a></article><?php endforeach;?><div class="u-pagination"><span>Page <?=$pn?></span><div><?php if($pn>1):?><a href="apply.php?page=dashboard&p=<?=$pn-1?>">← Previous</a><?php endif;if($more):?><a href="apply.php?page=dashboard&p=<?=$pn+1?>">Next →</a><?php endif;?></div></div>
<?php elseif($page==='application'):$a=$application;$d=json_decode($a['data_json'],true,512,JSON_THROW_ON_ERROR);$events=rows('SELECT actor,message,created_at FROM application_events WHERE application_id=? ORDER BY id DESC LIMIT 100',[$a['id']]);?>
<section class="u-card"><div class="u-eyebrow">APPLICATION ACKNOWLEDGEMENT</div><h1><?=e($a['reference'])?></h1><p><strong><?=e($a['status'])?></strong> · Submitted <?=e($a['submitted_at'])?></p><dl class="u-dl"><?php foreach(['name'=>'Applicant','institute_name'=>'Institute','course_name'=>'Course','duration'=>'Duration','father_name'=>"Father's name",'mother_name'=>"Mother's name",'date_of_birth'=>'Date of birth','gender'=>'Gender','category'=>'Category','nationality'=>'Nationality','phone'=>'Phone','city'=>'City','board_10'=>'Class 10 board','year_10'=>'Class 10 year','roll_10'=>'Class 10 roll','obtained_10'=>'Class 10 obtained','total_10'=>'Class 10 total','percentage_10'=>'Class 10 %','board_12'=>'Class 12 board','year_12'=>'Class 12 year','stream_12'=>'Class 12 stream','roll_12'=>'Class 12 roll','obtained_12'=>'Class 12 obtained','total_12'=>'Class 12 total','percentage_12'=>'Class 12 %','qualification'=>'Qualification','completion_year'=>'Completed in','note'=>'Additional information'] as $key=>$label):?><div><dt><?=e($label)?></dt><dd><?=e((string)($d[$key]??''))?></dd></div><?php endforeach;?><div><dt>Verified email</dt><dd><?=e($actor['email'])?></dd></div><div><dt>Fee quoted on submission</dt><dd>₹<?=number_format((int)$a['fee_minor']/100,2)?></dd></div></dl><p class="u-small">You may print this page using your browser. This acknowledgement is not a payment receipt or an admission guarantee.</p>
<?php if($a['status']==='Admitted'):?><div class="u-alert"><strong>Your admission has been approved.</strong> Student portal access was enabled at approval. If access is later disabled, contact the office. Sign in separately with your verified email to see your admission letter, fees and other records. The admission-letter email is queued and depends on the institute's notification worker.</div><a class="u-btn solid" href="student.php">Open my student portal →</a><?php elseif($a['status']==='Rejected'):?><p>Read the office decision below. Contact the institute if you need clarification. This application cannot be edited or reopened.</p><?php elseif($a['status']==='Withdrawn'):?><p>You withdrew this application. You may browse courses and submit a new application if eligible.</p><?php else:?><p>The institute must review your eligibility and documents. Check here for the authoritative status; updates are also queued for email, but delivery depends on the institute mail worker.</p><?php endif;?><details><summary>Privacy notice accepted with this application</summary><p><?=nl2br(e($a['consent_notice']))?></p><small><?=e($a['consent_version'])?></small></details></section>
<?php if(function_exists('automationReady')&&automationReady()):$certs=rows('SELECT * FROM certificates WHERE application_id=? ORDER BY id',[$a['id']]);?>
<section class="u-card"><h2>Certificate uploads</h2><p class="u-small">PDF, JPEG or PNG up to 5 MB each, maximum ten. Uploads are quarantined until the office scans and verifies them. Do not upload government ID numbers or medical records unless the office explicitly asks.</p><?php if(!$certs):?><p class="u-small">No certificates uploaded yet.</p><?php else:?><div class="u-table-wrap"><table><thead><tr><th>File</th><th>Uploaded</th><th>Scan</th><th>Office review</th><th></th></tr></thead><tbody><?php foreach($certs as $c):?><tr><td><?=e($c['original_name'])?> <small><?=e(wizardDocLabel((string)($c['doc_type']??'certificate')))?> · <?=e($c['mime'])?> · <?=number_format((int)$c['bytes']/1024,1)?> KB</small></td><td><?=e($c['created_at'])?></td><td><?=e($c['scan_state'])?></td><td><?=e($c['review_state'])?></td><td><a href="apply.php?certificate=<?=(int)$c['id']?>">Download ↓</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<?php if(!in_array($a['status'],['Admitted','Rejected','Withdrawn'],true)&&count($certs)<10):?><?=apUploadForm('upload_certificate')?><div class="u-form"><input type="hidden" name="application_id" value="<?=(int)$a['id']?>"><input type="hidden" name="version" value="<?=(int)$a['version']?>"><label>Choose certificate<input type="file" name="certificate" accept=".pdf,.jpg,.jpeg,.png" required></label><button class="u-btn solid">Upload for office verification →</button></div></form><?php elseif(count($certs)>=10):?><p class="u-small">Upload limit reached. Contact the office for help.</p><?php endif;?></section><?php endif;?>
<?php if(in_array($a['status'],['Changes requested','Revision'],true)):?><section class="u-card"><h2>Correct and resubmit</h2><p>Read the office's requested changes below. Email, institute, course and quoted fee cannot be changed here. You can also attach missing documents in step 3.</p><?=apUploadForm('revise_application')?><div class="u-form"><input type="hidden" name="application_id" value="<?=(int)$a['id']?>"><input type="hidden" name="version" value="<?=(int)$a['version']?>"><?php applicationFormFields($d,$a['consent_notice'],'revise');?></div></form></section><?php endif;?>
<section class="u-card"><h2>Latest 100 application updates</h2><?php foreach($events as $ev):?><article class="u-message"><strong><?=e($ev['actor'])?></strong><p class="u-small"><?=e($ev['created_at'])?></p><p><?=nl2br(e($ev['message']))?></p></article><?php endforeach;?></section>
<?php if(!in_array($a['status'],['Admitted','Rejected','Withdrawn'],true)):?><section class="u-card"><details><summary>Withdraw this application</summary><?=apForm('withdraw_application')?><div class="u-form"><input type="hidden" name="application_id" value="<?=(int)$a['id']?>"><input type="hidden" name="version" value="<?=(int)$a['version']?>"><?php apField('Reason for withdrawal','reason','',500);?><p>Withdrawal closes this application. It does not cancel an already approved admission or refund a payment.</p><button class="u-btn solid">Confirm withdrawal</button></div></form></details></section><?php endif;?>
<?php elseif($page==='help'):?>
<section class="u-card"><h1>Your admission journey</h1><ol><li>Browse a course opened by your institute. Read eligibility, fee information and its privacy notice.</li><li>Verify your own email with a one-time code.</li><li>Submit accurate contact and qualification details. Keep your application reference.</li><li>Upload certificates from your application page when enabled. Uploads are quarantined until scanned and verified.</li><li>Return to My applications to track review and respond to correction requests. Status updates are queued for email, but this page is authoritative.</li><li>The office verifies eligibility and original documents before approving or rejecting admission. Some courses use owner-authorized automatic checks after certificate verification.</li><li>After approval, sign in to the enrolled-student portal for your admission letter, payments, installments, attendance, published results, notices and support.</li></ol><h2>Before you apply</h2><p>There is no guaranteed seat. Payments are collected only after admission through the enrolled-student portal, never on this application page. Contact the institute using the phone on its course page. Do not send government ID numbers, medical records, card details, passwords or OTPs in application notes.</p><h2>Already enrolled?</h2><p><a href="student.php">Use the student portal</a>. If access is disabled or your email is incorrect, contact the office. Applying again does not repair an existing student account.</p><h2>Email and privacy</h2><p>Use a personal email you control, not a shared family address. One active application per applicant is supported. An email cannot be used to create multiple student portal enrolments. Minors should contact the office about its guardian-consent process. Check the institute notice for privacy and retention information.</p></section>
<?php elseif($page==='unavailable'):?><section class="u-card"><h1>Online admissions are not ready</h1><p>The institute must complete its upgrade or resolve a server issue. Please contact the office.</p></section>
<?php else:?><section class="u-card"><h1>Page or application unavailable</h1><p>This record is not accessible, or the course is no longer accepting new applications.</p><a href="apply.php">Return to open courses →</a></section><?php endif;?>
</main><?=siteFooter($apBrand,$apKind,$apCity,$apAddr,$apPhone)?><p class="u-footnote"><?=siteBackLink()?></p></body></html>
