<?php
declare(strict_types=1);
requireRole(['owner','admin']);
if(!operationsReady()) { echo '<section class="panel"><div class="panel-heading"><div><h2>Operations upgrade required</h2><p>Back up first, then ask the group owner to open the upgrade page.</p><a class="text-link" href="upgrade.php">Open upgrade →</a></div></div></section>'; return; }
$pn=max(1,(int)($_GET['p']??1));$offset=($pn-1)*30;
$fi=(int)($_GET['form_institute']??($scope?:($institutes[0]['id']??0)));if($fi)instituteAccess($fi);
$edit=(int)($_GET['edit']??0);$r=[];
if($edit && in_array($page,['teachers','batches'],true)){$r=opsRecord($page,$edit);$fi=(int)$r['institute_id'];}
function opsContext(string $page,array $institutes,int $fi): void {
    echo '<form method="get" class="form-context"><input type="hidden" name="page" value="'.e($page).'">';selectField('Working institute','form_institute',options($institutes),$fi);echo '<button class="button secondary">Load institute</button></form><p class="form-hint">Load the institute before selecting a course, batch or student.</p>';
}
function opsExport(string $report,int $iid=0,int $class=0): string {return '<form method="post" action="export.php">'.csrf().'<input type="hidden" name="report" value="'.e($report).'"><input type="hidden" name="institute_id" value="'.$iid.'"><input type="hidden" name="class_id" value="'.$class.'"><button class="button secondary">Download CSV ↓</button></form>';}
if($page==='teachers'):
?>
<section class="panel editor"><div class="panel-heading"><div><h2><?=$edit?'Edit teacher':'Add teacher'?></h2><p>Teacher directory only. Teachers do not receive staff logins in this phase.</p></div></div><?php if(!$edit)opsContext($page,$institutes,$fi);formStart('teacher',$edit);?><input type="hidden" name="institute_id" value="<?=$fi?>"><div class="form-grid"><?php field('Full name','name',$r['name']??'');field('Phone','phone',$r['phone']??'','tel');field('Email (optional)','email',$r['email']??'','email',false);field('Qualification / specialization (optional)','qualification',$r['qualification']??'','text',false);selectField('Status','active',['1'=>'Active','0'=>'Inactive'],$r['active']??'1'); ?></div><?php formEnd('Save teacher'); ?></section>
<section class="panel"><?php $list=rows("SELECT t.*,i.name institute_name FROM teachers t JOIN institutes i ON i.id=t.institute_id WHERE ".($scope?'t.institute_id=?':'1=1')." ORDER BY t.id DESC LIMIT 31 OFFSET $offset",$args);$more=count($list)>30;$list=array_slice($list,0,30);table(['Teacher','Institute','Qualification','Status',''],$list,fn($t)=>[person($t['name'],$t['email']),e($t['institute_name']),e($t['qualification']),badge($t['active']?'Active':'Inactive'),editLink('teachers',(int)$t['id'])]); ?>
<?php elseif($page==='batches'):
$cs=$fi?rows('SELECT * FROM courses WHERE institute_id=? ORDER BY name',[$fi]):[];$ts=$fi?rows('SELECT * FROM teachers WHERE institute_id=? ORDER BY name',[$fi]):[];
$bs=$fi?rows('SELECT b.*,c.name course_name FROM batches b JOIN courses c ON c.id=b.course_id WHERE b.institute_id=? AND b.active=1 ORDER BY b.name',[$fi]):[];
$ss=$fi?rows('SELECT s.*,c.name course_name FROM students s JOIN courses c ON c.id=s.course_id WHERE s.institute_id=? ORDER BY s.name',[$fi]):[];
foreach($bs as &$b)$b['name'].=' · '.$b['course_name'];unset($b);foreach($ss as &$s)$s['name'].=' · ST-'.$s['id'].' · '.$s['course_name'];unset($s);
?>
<?php if(isset($_GET['roster'])): $rb=opsRecord('batches',(int)$_GET['roster']); $members=rows('SELECT e.*,s.name,s.phone FROM enrollments e JOIN students s ON s.id=e.student_id WHERE e.batch_id=? ORDER BY e.starts_on DESC,e.id DESC LIMIT 500',[$rb['id']]); ?><section class="panel"><div class="panel-heading"><div><h2><?=e($rb['name'])?> · Allocation history</h2><p>Up to 500 latest allocations. Attendance preserves its own historical rosters.</p></div></div><?php table(['Student','From','Through'],$members,fn($m)=>[person($m['name'],$m['phone']),e($m['starts_on']),e($m['ends_on']??'Current allocation')]); ?></section><?php endif; ?>
<section class="panel editor"><div class="panel-heading"><div><h2><?=$edit?'Edit batch':'Create batch'?></h2><p>Capacity is enforced. Course, institute and dates are fixed once created.</p></div></div><?php if(!$edit)opsContext($page,$institutes,$fi);formStart('batch',$edit);?><input type="hidden" name="institute_id" value="<?=$fi?>"><div class="form-grid"><?php field('Batch name','name',$r['name']??'');selectField('Course','course_id',options($cs),$r['course_id']??'');selectField('Teacher','teacher_id',options($ts),$r['teacher_id']??'');field('Room (optional)','room',$r['room']??'','text',false);field('Start date','starts_on',$r['starts_on']??date('Y-m-d'),'date');field('End date','ends_on',$r['ends_on']??'','date');field('Capacity (1–500)','capacity',$r['capacity']??'40','number');selectField('Status','active',['1'=>'Active','0'=>'Archived'],$r['active']??'1'); ?></div><?php formEnd('Save batch'); ?></section>
<section class="panel editor"><div class="panel-heading"><div><h2>Allocate / transfer a student</h2><p>One active batch per student. Prior allocation and attendance history are retained. Select the institute above first.</p></div></div><?php formStart('enrollment');?><div class="form-grid"><?php selectField('Student','student_id',options($ss));selectField('Destination batch','batch_id',options($bs));field('Allocation / transfer date','starts_on',date('Y-m-d'),'date'); ?></div><?php formEnd('Save allocation'); ?></section>
<section class="panel"><?php $list=rows("SELECT b.*,c.name course_name,t.name teacher_name,(SELECT COUNT(*) FROM enrollments e WHERE e.batch_id=b.id AND e.ends_on IS NULL) allocated FROM batches b JOIN courses c ON c.id=b.course_id JOIN teachers t ON t.id=b.teacher_id WHERE ".($scope?'b.institute_id=?':'1=1')." ORDER BY b.id DESC LIMIT 31 OFFSET $offset",$args);$more=count($list)>30;$list=array_slice($list,0,30);table(['Batch / course','Teacher','Dates','Allocation','Status',''],$list,fn($b)=>['<strong>'.e($b['name']).'</strong><small>'.e($b['course_name']).'</small>',e($b['teacher_name']),e($b['starts_on']).'<small>to '.e($b['ends_on']).'</small>',e($b['allocated']).' / '.e($b['capacity']),badge($b['active']?'Active':'Archived'),editLink('batches',(int)$b['id']).'<br><a class="text-link" href="?page=batches&roster='.$b['id'].'">View allocation history ↗</a>']); ?>
<?php elseif($page==='attendance'):
$bs=rows("SELECT * FROM batches WHERE $where AND active=1 ORDER BY name",$args);
$cid=(int)($_GET['class']??0);
if($cid): $c=opsRecord('class_days',$cid);$roster=rows('SELECT a.*,s.name FROM attendance a JOIN students s ON s.id=a.student_id WHERE a.class_id=? ORDER BY s.name',[$cid]);
?>
<section class="panel editor"><div class="panel-heading"><div><h2>Attendance · <?=e($c['held_on'])?></h2><p><?=e($c['topic'])?> · Teacher snapshot: <?=e($c['teacher_name'])?> · Version <?=(int)$c['version']?></p></div><?=opsExport('attendance',0,$cid)?></div>
<?php formStart('attendance');?><input type="hidden" name="class_id" value="<?=$cid?>"><input type="hidden" name="version" value="<?=$c['version']?>"><div class="form-grid"><?php foreach($roster as $a)selectField($a['name'].' · ST-'.$a['student_id'],'attendance['.$a['student_id'].']',['Present'=>'Present','Absent'=>'Absent','Late'=>'Late','Excused'=>'Excused'],$a['status']);textArea($c['finalized']?'Correction reason (required)':'Notes / reason (optional)','reason','',(bool)$c['finalized']); ?></div><?php formEnd($c['finalized']?'Save audited correction':'Finalize attendance'); ?></section>
<section class="panel"><div class="panel-heading"><h2>Attendance change history</h2></div><?php $revs=rows('SELECT r.*,u.name FROM attendance_revisions r JOIN users u ON u.id=r.recorded_by WHERE class_id=? ORDER BY r.id DESC LIMIT 20',[$cid]);table(['Time','Recorded by','Reason'],$revs,fn($v)=>[e($v['created_at']),e($v['name']),e($v['reason'])]); ?></section>
<?php else: ?>
<section class="panel editor"><div class="panel-heading"><div><h2>Open daily attendance</h2><p>One class record per batch per day. Rosters are frozen at creation; unmarked drafts do not affect reports.</p></div></div><?php formStart('class_day');?><div class="form-grid"><?php selectField('Batch','batch_id',options($bs));field('Class date','held_on',date('Y-m-d'),'date');field('Topic / class description','topic'); ?></div><?php formEnd('Create class roster'); ?></section>
<?php endif; ?>
<section class="panel"><?php $list=rows("SELECT c.*,b.name batch_name,(SELECT COUNT(*) FROM attendance a WHERE a.class_id=c.id) roster_count FROM class_days c JOIN batches b ON b.id=c.batch_id WHERE ".($scope?'c.institute_id=?':'1=1')." ORDER BY c.held_on DESC,c.id DESC LIMIT 31 OFFSET $offset",$args);$more=count($list)>30;$list=array_slice($list,0,30);table(['Class date','Batch / topic','Students','Status',''],$list,fn($c)=>[e($c['held_on']),'<strong>'.e($c['batch_name']).'</strong><small>'.e($c['topic']).'</small>',e($c['roster_count']),badge($c['finalized']?'Finalized':'Draft'),'<a class="text-link" href="?page=attendance&class='.$c['id'].'">Open roster ↗</a>']); ?>
<?php elseif($page==='fee-plans'):
$ss=rows("SELECT * FROM students WHERE $where ORDER BY name",$args);foreach($ss as &$s)$s['name'].=' · ST-'.$s['id'];unset($s);
$sid=(int)($_GET['student']??0);
?>
<section class="panel editor"><div class="panel-heading"><div><h2>Installment schedule</h2><p>Schedule the full agreed course fee, including money already received. Payments cover earliest installments first.</p></div></div><form method="get" class="form-context"><input type="hidden" name="page" value="fee-plans"><?php selectField('Student','student',options($ss),$sid);?><button class="button secondary">Load student</button></form>
<?php if($sid):$s=record('students',$sid);$plan=one('SELECT * FROM fee_plans WHERE student_id=?',[$sid]);$items=$plan?rows('SELECT * FROM fee_installments WHERE plan_id=? ORDER BY due_on',[$plan['id']]):[];
?><p class="inline-note"><strong><?=e($s['name'])?></strong> · Agreed admission fee: <?=money((int)$s['fee_minor'])?>. Up to 36 dates; blank rows are ignored. Every save needs a reason and retains a before/after history.</p>
<?php formStart('fee_plan');?><input type="hidden" name="student_id" value="<?=$sid?>"><input type="hidden" name="version" value="<?=$plan['version']??0?>"><div id="installment-rows"><?php for($n=0;$n<max(6,count($items));$n++):?><div class="installment-row"><label>Due date<input type="date" name="due_on[]" value="<?=e($items[$n]['due_on']??'')?>"></label><label>Amount (INR)<input name="installment_amount[]" inputmode="decimal" value="<?=isset($items[$n])?e(number_format($items[$n]['amount_minor']/100,2,'.','')):''?>" maxlength="12"></label></div><?php endfor;?></div><button type="button" class="button secondary" id="add-installment">＋ Add installment row</button><?php textArea('Reason for creating / changing schedule','reason','',true);formEnd('Save fee schedule'); ?>
</section><section class="panel"><div class="panel-heading"><h2>Current allocation of payments</h2></div><?php table(['Due date','Installment','Covered','Remaining','Status'],studentInstallments($sid),fn($i)=>[e($i['due_on']),money((int)$i['amount_minor']),money((int)$i['paid_minor']),money((int)$i['balance_minor']),badge($i['status'])]); ?></section><section class="panel"><div class="panel-heading"><h2>Schedule revision history</h2></div><?php $revs=$plan?rows('SELECT r.*,u.name FROM fee_plan_revisions r JOIN users u ON u.id=r.recorded_by WHERE plan_id=? ORDER BY r.id DESC LIMIT 20',[$plan['id']]):[];table(['Time','Changed by','Reason'],$revs,fn($v)=>[e($v['created_at']),e($v['name']),e($v['reason'])]); ?></section>
<?php else: ?><div class="empty">Load a student to create or revise the fee schedule.</div></section><?php endif;return; ?>
<?php elseif($page==='fee-reports'):
$list=feeReportRows($scope,31,$offset);$more=count($list)>30;$list=array_slice($list,0,30);
?>
<section class="panel"><div class="panel-heading"><div><h2>Outstanding & overdue fees</h2><p>Overdue = installments due before today, minus all recorded payments, floored at zero. No schedule means no computed overdue amount.</p></div><?=opsExport('fees',$scope)?></div><?php table(['Student / institute','Agreed fee','Paid','Total unpaid','Overdue','Schedule'],$list,fn($s)=>[person($s['name'],$s['institute_name']),money((int)$s['fee_minor']),money((int)$s['paid_minor']),money((int)$s['fee_minor']-(int)$s['paid_minor']),$s['plan_id']?money(max(0,(int)$s['scheduled_before_today']-(int)$s['paid_minor'])):'Not scheduled','<a class="text-link" href="?page=fee-plans&student='.$s['id'].'">'.($s['plan_id']?'View schedule':'Create schedule').' ↗</a>']); ?>
<?php elseif($page==='health'):
requireRole(['owner']);global $config;
$checks=[
 ['Runtime','PHP '.PHP_VERSION,'Use a supported, patched PHP version; keep extensions and dependencies updated.'],
 ['Environment',$config['environment']??'Not set','Production should use environment=production.'],
 ['Secure cookies',!empty($config['secure_cookies'])?'Enabled':'Not enabled','Enable secure cookies and HTTPS before remote student access.'],
 ['Mail transport',$config['mail']['transport']??'Not configured','SMTP settings must be tested on the real server. Local capture never delivers to an inbox.'],
 ['Database',db()->getAttribute(PDO::ATTR_DRIVER_NAME),'Use a dedicated least-privilege account. MySQL/MariaDB must be tested on your hosting stack.'],
 ['Failed email notifications',(string)query("SELECT COUNT(*) FROM notifications WHERE status='failed'")->fetchColumn(),'Check SMTP and dependencies, then requeue failed items in Email notifications.'],
 ['Pending email notifications',(string)query("SELECT COUNT(*) FROM notifications WHERE status IN ('pending','sending')")->fetchColumn(),'Schedule the worker every minute. Queue counts alone do not prove it is running.'],
 ['Backups & restore','External setup required','No automatic backup or restore verification is bundled. Schedule encrypted backups and test a restore into a separate database.'],
 ['Monitoring & security audit','External review required','These checks are informational, not a production certification or vulnerability scan.']
];
?>
<section class="panel"><div class="panel-heading"><div><h2>Deployment readiness checks</h2><p>Owner-only operational checklist. Credentials and private filesystem paths are never shown.</p></div></div><?php table(['Check','Observed value','Required action'],$checks,fn($c)=>[e($c[0]),e($c[1]),'<span class="notes">'.e($c[2]).'</span>']); ?></section><p class="footnote">A successful install or passing tests does not make a public deployment automatically safe. Complete the production checklist in docs/OPERATIONS.md.</p><?php return; endif; ?>
<div class="pagination"><span>Page <?=$pn?></span><div><?php if($pn>1):?><a class="button secondary" href="<?=e(url(['p'=>$pn-1]))?>">← Previous</a><?php endif;?><?php if($more):?><a class="button secondary" href="<?=e(url(['p'=>$pn+1]))?>">Next →</a><?php endif;?></div></div></section>
