<?php
declare(strict_types=1);
requireRole(['owner','admin']);
if(!servicesReady()){echo '<section class="panel"><div class="panel-heading"><div><h2>Student services upgrade required</h2><p>Back up first, then open the owner upgrade page.</p><a href="upgrade.php">Upgrade installed modules →</a></div></div></section>';return;}
$pn=min(100000,max(1,(int)($_GET['p']??1)));$offset=($pn-1)*20;$fi=(int)($_GET['form_institute']??($scope?:($institutes[0]['id']??0)));if($fi)instituteAccess($fi);
function serviceContext(string $page,array $institutes,int $fi): void {echo '<form method="get" class="form-context"><input type="hidden" name="page" value="'.e($page).'">';selectField('Working institute','form_institute',options($institutes),$fi);echo '<button class="button secondary">Load institute</button></form>';}
function scoreDisplay(?int $n): string {return $n===null?'—':number_format($n/100,2,'.','');}
function serviceHistory(string $table,string $key,int $id): void {
    $list=rows("SELECT r.*,u.name FROM $table r JOIN users u ON u.id=r.actor_id WHERE $key=? ORDER BY r.id DESC LIMIT 20",[$id]);
    echo '<section class="panel"><div class="panel-heading"><h2>Latest 20 revisions</h2></div>';
    table(['Time / actor','Reason','Snapshot'],$list,fn($r)=>[person($r['name'],$r['created_at']),e($r['reason']),'<details><summary>View before / after</summary><pre class="revision-json">'.e(json_encode(json_decode($r['snapshot_json'],true),JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)).'</pre></details>']);echo '</section>';
}
if($page==='exams'):
if(isset($_GET['exam'])):
    $exam=serviceRecord('exams',(int)$_GET['exam']);$roster=rows('SELECT r.*,s.name FROM exam_results r JOIN students s ON s.id=r.student_id WHERE exam_id=? ORDER BY s.name,s.id',[$exam['id']]);
?>
<section class="panel"><div class="panel-heading"><div><h2><?=e($exam['title'])?> · <?=e($exam['state'])?></h2><p><?=e($exam['held_on'])?> · Maximum <?=scoreDisplay((int)$exam['maximum_minor'])?> · Pass <?=scoreDisplay((int)$exam['pass_minor'])?> · Version <?=(int)$exam['version']?></p></div><a href="?page=exams">All exams →</a></div>
<div class="settings-body"><?php if($exam['state']==='Draft'):formStart('exam_grade');?><input type="hidden" name="exam_id" value="<?=(int)$exam['id']?>"><input type="hidden" name="version" value="<?=(int)$exam['version']?>"><p>Complete every row. Leave marks blank for absent students. Saving does not publish results.</p><div class="table-wrap"><table><thead><tr><th>Student</th><th>Attendance</th><th>Marks</th></tr></thead><tbody><?php foreach($roster as $r):?><tr><td><?=e($r['name'])?><small>ST-<?=str_pad((string)$r['student_id'],5,'0',STR_PAD_LEFT)?></small></td><td><select name="result_status[<?=(int)$r['student_id']?>]" aria-label="Attendance for <?=e($r['name'])?>" required><option value="">Choose</option><?php foreach(['Present','Absent'] as $v):?><option <?=$v===$r['attendance']?'selected':''?>><?=$v?></option><?php endforeach;?></select></td><td><input aria-label="Marks for <?=e($r['name'])?>" name="marks[<?=(int)$r['student_id']?>]" type="number" min="0" max="<?=scoreDisplay((int)$exam['maximum_minor'])?>" step="0.01" value="<?=$r['score_minor']===null?'':scoreDisplay((int)$r['score_minor'])?>"></td></tr><?php endforeach;?></tbody></table></div><?php field('Reason for this mark entry / correction','reason','','text');formEnd('Save draft marks');else:table(['Student','Attendance','Marks'],$roster,fn($r)=>[e($r['name']),e($r['attendance']),scoreDisplay($r['score_minor']===null?null:(int)$r['score_minor'])]);endif;?><hr>
<?php formStart('exam_publish');?><input type="hidden" name="exam_id" value="<?=(int)$exam['id']?>"><input type="hidden" name="version" value="<?=(int)$exam['version']?>"><input type="hidden" name="state" value="<?=$exam['state']==='Published'?'Draft':'Published'?>"><?php field('Publication / withdrawal reason','reason');formEnd($exam['state']==='Published'?'Withdraw results from student portal':'Publish complete results to students');?><p class="form-hint">Withdrawal hides all results for this exam. Correct marks in draft, then publish again. Every change is retained; no email is sent.</p></div></section>
<?php serviceHistory('exam_revisions','exam_id',(int)$exam['id']);return;endif;
$batches=$fi?rows('SELECT id,name FROM batches WHERE institute_id=? ORDER BY name',[$fi]):[];
?>
<section class="panel editor"><div class="panel-heading"><div><h2>Create a completed assessment</h2><p>One subject or assessment per exam. Freeze 1–200 students eligible on the exam date; definitions cannot be edited afterward.</p></div></div><?php serviceContext($page,$institutes,$fi);formStart('exam_create');?><div class="form-grid"><?php selectField('Batch','batch_id',options($batches));field('Exam / subject title','title');field('Exam date','held_on',date('Y-m-d'),'date');field('Maximum marks (up to two decimals)','maximum','100');field('Pass marks (up to two decimals)','pass_mark','40');?></div><?php formEnd('Create draft exam');?></section>
<?php $data=rows('SELECT x.*,b.name batch_name FROM exams x JOIN batches b ON b.id=x.batch_id WHERE '.($scope?'x.institute_id=?':'1=1').' ORDER BY x.held_on DESC,x.id DESC LIMIT 21 OFFSET '.$offset,$args);$more=count($data)>20;$data=array_slice($data,0,20);?>
<section class="panel"><div class="panel-heading"><h2>Assessment register</h2></div><?php table(['Exam / batch','Date','State',''],$data,fn($r)=>[person($r['title'],$r['batch_name']),e($r['held_on']),badge($r['state']),'<a href="?page=exams&exam='.$r['id'].'">Open marks & history →</a>']);?>
<?php elseif($page==='announcements'):
$id=(int)($_GET['edit']??0);$r=$id?serviceRecord('announcements',$id):[];if($r)$fi=(int)$r['institute_id'];$bs=$fi?rows('SELECT id,name FROM batches WHERE institute_id=? ORDER BY name',[$fi]):[];
?>
<section class="panel editor"><div class="panel-heading"><div><h2><?=$id?'Edit announcement':'Post an announcement'?></h2><p>Student portal notices only. Visibility uses institute, optional current batch, publication state and inclusive date range. No email/SMS is sent.</p></div></div><?php if(!$id)serviceContext($page,$institutes,$fi);formStart('announcement',$id);?><input type="hidden" name="institute_id" value="<?=$fi?>"><input type="hidden" name="version" value="<?=(int)($r['version']??0)?>"><div class="form-grid"><?php field('Title','title',$r['title']??'');selectField('Audience','batch_id',[0=>'All institute students']+options($bs),$r['batch_id']??0);field('Show from','starts_on',$r['starts_on']??date('Y-m-d'),'date');field('Show through','ends_on',$r['ends_on']??date('Y-m-d',strtotime('+30 days')),'date');selectField('State','state',['Draft'=>'Draft','Published'=>'Published','Archived'=>'Archived'],$r['state']??'Draft');?></div><label>Message (plain text, maximum 5000 bytes)<textarea name="body" rows="6" maxlength="5000" required><?=e($r['body']??'')?></textarea></label><?php field('Reason for creation / change','reason');formEnd('Save announcement');?></section>
<?php if($id){serviceHistory('announcement_revisions','announcement_id',$id);return;}
$data=rows('SELECT * FROM announcements WHERE '.($scope?'institute_id=?':'1=1').' ORDER BY id DESC LIMIT 21 OFFSET '.$offset,$args);$more=count($data)>20;$data=array_slice($data,0,20);?>
<section class="panel"><div class="panel-heading"><h2>Notice board</h2></div><?php table(['Title','Visibility','State',''],$data,fn($r)=>[e($r['title']),e($r['starts_on'].' → '.$r['ends_on']),badge($r['state']),editLink('announcements',(int)$r['id'])]);?>
<?php elseif($page==='support'):
$_SESSION['support_nonce']??=bin2hex(random_bytes(24));
if(isset($_GET['ticket'])):$ticket=serviceRecord('support_tickets',(int)$_GET['ticket']);$s=record('students',(int)$ticket['student_id']);$messages=rows('SELECT m.*,u.name staff_name FROM support_messages m LEFT JOIN users u ON u.id=m.staff_id WHERE ticket_id=? ORDER BY m.id',[$ticket['id']]);?>
<section class="panel"><div class="panel-heading"><div><h2>#<?=(int)$ticket['id']?> · <?=e($ticket['subject'])?></h2><p><?=e($s['name'])?> · <?=e($ticket['category'])?> · <?=e($ticket['status'])?></p></div><a href="?page=support">All tickets →</a></div><div class="settings-body"><?php foreach($messages as $m):?><article class="support-message"><strong><?=e($m['staff_id']?$m['staff_name']:'Student')?></strong><small><?=e($m['created_at'])?></small><p><?=nl2br(e($m['body']))?></p></article><?php endforeach;formStart('support_reply');?><input type="hidden" name="ticket_id" value="<?=(int)$ticket['id']?>"><input type="hidden" name="version" value="<?=(int)$ticket['version']?>"><input type="hidden" name="request_key" value="<?=e($_SESSION['support_nonce'])?>"><label>Reply visible to the student<textarea name="body" rows="5" maxlength="3000" required></textarea></label><?php selectField('Ticket status after reply','status',['Open'=>'Open','Waiting'=>'Waiting for student','Resolved'=>'Resolved'],$ticket['status']);formEnd('Send reply');?><p class="form-hint">Every reply is retained. No private/internal notes or email alerts are supported. Staff can reopen a resolved conversation by replying with Open status.</p></div></section>
<?php return;endif;
$filter=is_string($_GET['status']??null)?$_GET['status']:'';if(!in_array($filter,['','Open','Waiting','Resolved'],true))$filter='';$where=$scope?'t.institute_id=?':'1=1';$ta=$args;if($filter){$where.=' AND t.status=?';$ta[]=$filter;}
$data=rows('SELECT t.*,s.name FROM support_tickets t JOIN students s ON s.id=t.student_id WHERE '.$where.' ORDER BY t.updated_at DESC,t.id DESC LIMIT 21 OFFSET '.$offset,$ta);$more=count($data)>20;$data=array_slice($data,0,20);?>
<section class="panel"><div class="panel-heading"><div><h2>Student help desk</h2><p>Check this inbox regularly. Students see replies in the portal; there are no automatic alerts or SLA guarantees.</p></div></div><form class="search-form list-toolbar" method="get"><input type="hidden" name="page" value="support"><input type="hidden" name="institute" value="<?=$scope?>"><?php selectField('Status','status',[''=>'All statuses','Open'=>'Open','Waiting'=>'Waiting','Resolved'=>'Resolved'],$filter,false);?><button class="button secondary">Filter</button></form><?php table(['Ticket / student','Category','Status','Last activity',''],$data,fn($r)=>[person('#'.$r['id'].' '.$r['subject'],$r['name']),e($r['category']),badge($r['status']),e($r['updated_at']),'<a href="?page=support&ticket='.$r['id'].'">Open conversation →</a>']);?>
<?php endif;?>
<div class="pagination"><span>Page <?=$pn?></span><div><?php if($pn>1):?><a class="button secondary" href="<?=e(url(['p'=>$pn-1]))?>">← Previous</a><?php endif;?><?php if($more):?><a class="button secondary" href="<?=e(url(['p'=>$pn+1]))?>">Next →</a><?php endif;?></div></div></section>
