<?php
declare(strict_types=1);
if(!operationsReady()){echo '<section class="sp-card"><h2>Academic records are not enabled yet</h2><p>Your institute needs to complete the operations upgrade.</p></section>';return;}
$sid=(int)$student['id'];
$enrollments=rows('SELECT e.*,b.name,b.room,b.starts_on batch_start,b.ends_on batch_end,t.name teacher_name FROM enrollments e JOIN batches b ON b.id=e.batch_id JOIN teachers t ON t.id=b.teacher_id WHERE e.student_id=? ORDER BY e.starts_on DESC,e.id DESC',[$sid]);
$counts=rows('SELECT a.status,COUNT(*) total FROM attendance a JOIN class_days c ON c.id=a.class_id WHERE a.student_id=? AND c.finalized=1 GROUP BY a.status',[$sid]);$counts=array_column($counts,'total','status');
$present=(int)($counts['Present']??0);$late=(int)($counts['Late']??0);$absent=(int)($counts['Absent']??0);$denom=$present+$late+$absent;$percent=$denom?number_format(($present+$late)*100/$denom,1).'%':'Not yet available';
$pn=max(1,(int)($_GET['p']??1));$records=rows('SELECT a.status,c.held_on,c.topic,c.teacher_name,b.name FROM attendance a JOIN class_days c ON c.id=a.class_id JOIN batches b ON b.id=c.batch_id WHERE a.student_id=? AND c.finalized=1 ORDER BY c.held_on DESC,c.id DESC LIMIT 21 OFFSET '.(($pn-1)*20),[$sid]);$more=count($records)>20;$records=array_slice($records,0,20);
?>
<div class="sp-stats three"><section class="sp-card sp-stat"><span>Attendance rate</span><strong><?=e($percent)?></strong></section><section class="sp-card sp-stat"><span>Present / late</span><strong><?=$present?> / <?=$late?></strong></section><section class="sp-card sp-stat"><span>Absent / excused</span><strong><?=$absent?> / <?=(int)($counts['Excused']??0)?></strong></section></div><p class="sp-footnote">Rate = (Present + Late) ÷ (Present + Late + Absent). Excused days and draft registers are excluded. These figures cover published class-day records, not subject periods.</p>
<section class="sp-card"><h2>Batch allocation history</h2><?php if(!$enrollments):?><p class="sp-small">Your institute has not allocated a batch yet.</p><?php else:foreach($enrollments as $en):?><dl><div><dt>Batch</dt><dd><?=e($en['name'])?></dd></div><div><dt>Allocation period</dt><dd><?=e($en['starts_on'])?> → <?=e($en['ends_on']??'Current allocation')?></dd></div><div><dt>Teacher / room</dt><dd><?=e($en['teacher_name'])?> · <?=e($en['room'])?></dd></div></dl><?php endforeach;endif;?></section><div class="sp-rule"></div>
<section class="sp-card sp-table-card"><div class="sp-table-head"><h2>Published attendance</h2><p>Only your own records are shown. Contact the office for corrections. Exams and marks are not available yet.</p></div><?php if(!$records):?><div class="sp-empty">No published attendance yet.</div><?php else:?><div class="sp-table-wrap"><table><thead><tr><th>Date</th><th>Batch / topic</th><th>Teacher</th><th>Status</th></tr></thead><tbody><?php foreach($records as $a):?><tr><td><?=e($a['held_on'])?></td><td><?=e($a['name'])?><small><?=e($a['topic'])?></small></td><td><?=e($a['teacher_name'])?></td><td><?=e($a['status'])?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?><div class="sp-pagination"><span>Page <?=$pn?></span><div><?php if($pn>1):?><a href="student.php?page=academics&p=<?=$pn-1?>">← Previous</a><?php endif;?><?php if($more):?><a href="student.php?page=academics&p=<?=$pn+1?>">Next →</a><?php endif;?></div></div></section>
