<?php
declare(strict_types=1);
if(!servicesReady()){echo '<section class="sp-card"><h2>Student services are not enabled yet</h2><p>Your institute needs to complete the upgrade.</p></section>';return;}
$pn=min(100000,max(1,(int)($_GET['p']??1)));$offset=($pn-1)*20;$more=false;
if($page==='results'):
$data=rows("SELECT r.attendance,r.score_minor,x.title,x.held_on,x.maximum_minor,x.pass_minor,b.name batch_name FROM exam_results r JOIN exams x ON x.id=r.exam_id JOIN batches b ON b.id=x.batch_id WHERE r.student_id=? AND x.institute_id=? AND x.state='Published' ORDER BY x.held_on DESC,x.id DESC LIMIT 21 OFFSET ".$offset,[$student['id'],$student['institute_id']]);$more=count($data)>20;$data=array_slice($data,0,20);
?>
<section class="sp-card sp-table-card"><div class="sp-table-head"><h2>Published assessments</h2><p>Only your own published marks are shown. An exam may temporarily disappear while the office corrects it. These are individual assessments, not an accredited certificate, GPA or official transcript.</p></div><?php if(!$data):?><div class="sp-empty">No published results yet.</div><?php else:?><div class="sp-table-wrap"><table><thead><tr><th>Assessment</th><th>Date</th><th>Marks / maximum</th><th>Outcome</th></tr></thead><tbody><?php foreach($data as $r):?><tr><td><?=e($r['title'])?><small><?=e($r['batch_name'])?></small></td><td><?=e($r['held_on'])?></td><td><?=$r['score_minor']===null?'—':number_format((int)$r['score_minor']/100,2)?> / <?=number_format((int)$r['maximum_minor']/100,2)?></td><td><?=e($r['attendance']==='Absent'?'Absent':((int)$r['score_minor']>=(int)$r['pass_minor']?'Pass':'Below pass mark'))?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<?php elseif($page==='announcements'):$data=studentAnnouncements($student,$offset);$more=count($data)>20;$data=array_slice($data,0,20);if(!$data):?><section class="sp-card"><h2>No current announcements</h2><p>Notices for your institute and current batch will appear here.</p></section><?php else:foreach($data as $r):?><article class="sp-card sp-notice"><h2><?=e($r['title'])?></h2><p class="sp-small"><?=e($r['starts_on'])?> → <?=e($r['ends_on'])?></p><p><?=nl2br(e($r['body']))?></p></article><?php endforeach;endif;?>
<?php elseif($page==='support'):
$_SESSION['support_nonce']??=bin2hex(random_bytes(24));
if(isset($_GET['ticket'])):
    $t=ticketForStudent($student,(int)$_GET['ticket']);$messages=rows('SELECT m.*,u.name staff_name FROM support_messages m LEFT JOIN users u ON u.id=m.staff_id WHERE ticket_id=? ORDER BY m.id',[$t['id']]);?>
<section class="sp-card"><a href="student.php?page=support">← My tickets</a><h2>#<?=(int)$t['id']?> · <?=e($t['subject'])?></h2><p><?=e($t['category'])?> · <?=e($t['status'])?></p><?php foreach($messages as $m):?><article class="sp-support-message"><strong><?=e($m['staff_id']?'Office · '.$m['staff_name']:'You')?></strong><p class="sp-small"><?=e($m['created_at'])?></p><p><?=nl2br(e($m['body']))?></p></article><?php endforeach;if($t['status']!=='Resolved'):?><?=spForm('support_reply')?><input type="hidden" name="ticket_id" value="<?=(int)$t['id']?>"><input type="hidden" name="version" value="<?=(int)$t['version']?>"><input type="hidden" name="request_key" value="<?=e($_SESSION['support_nonce'])?>"><label>Your reply<textarea name="body" rows="5" required maxlength="3000"></textarea></label><button class="sp-button">Send reply →</button></form><?php else:?><p>This ticket is resolved. Open a new request if further help is needed.</p><?php endif;?></section>
<?php return;endif;
$data=rows('SELECT * FROM support_tickets WHERE student_id=? AND institute_id=? ORDER BY updated_at DESC,id DESC LIMIT 21 OFFSET '.$offset,[$student['id'],$student['institute_id']]);$more=count($data)>20;$data=array_slice($data,0,20);?>
<section class="sp-card"><h2>Ask your institute</h2><p>For office enquiries only—not emergency or clinical care. Do not share passwords, OTPs, card numbers or medical records. Replies appear here; no email notification is sent.</p><?=spForm('support_create')?><input type="hidden" name="request_key" value="<?=e($_SESSION['support_nonce'])?>"><label>Subject<input name="subject" maxlength="150" required></label><label>Category<select name="category"><?php foreach(['General','Academic','Fees','Documents'] as $v):?><option><?=$v?></option><?php endforeach;?></select></label><label>Message<textarea name="body" rows="5" maxlength="3000" required></textarea></label><button class="sp-button">Open support ticket →</button></form><p class="sp-small">Up to five active tickets and 30 messages per hour. Each conversation supports up to 200 messages.</p></section><div class="sp-rule"></div>
<section class="sp-card"><h2>My conversations</h2><?php if(!$data):?><p>No support requests yet.</p><?php else:foreach($data as $r):?><article class="sp-support-message"><a href="student.php?page=support&ticket=<?=(int)$r['id']?>">#<?=(int)$r['id']?> · <?=e($r['subject'])?></a><p class="sp-small"><?=e($r['status'])?> · <?=e($r['updated_at'])?></p></article><?php endforeach;endif;?></section>
<?php endif;?>
<div class="sp-pagination"><span>Page <?=$pn?></span><div><?php if($pn>1):?><a href="student.php?page=<?=e($page)?>&p=<?=$pn-1?>">← Previous</a><?php endif;?><?php if($more):?><a href="student.php?page=<?=e($page)?>&p=<?=$pn+1?>">Next →</a><?php endif;?></div></div>
