<?php
declare(strict_types=1);
require_once __DIR__.'/site-chrome.php';
function spMoney(int $n): string { return '₹'.number_format($n/100,2); }
function spNumber(int $n): string { return 'ST-'.str_pad((string)$n,5,'0',STR_PAD_LEFT); }
function spForm(string $action): string { return '<form method="post">'.csrf().'<input type="hidden" name="action" value="'.e($action).'">'; }
[$spBrand,$spKind,$spCity,$spAddr,$spPhone]=siteBrand();
$spButtons=siteToggle();
<<<<<<< HEAD
if($student||$portalUser) $spButtons.=spForm('logout').'<button class="u-btn ghost" type="submit">Sign out ↗</button></form>';
else $spButtons.='<a class="u-btn ghost" href="index.php?page=login">Sign in ↗</a><a class="u-btn ghost" href="index.php?page=login&show=create">Create account ↗</a><a class="u-btn ghost" href="apply.php">Apply for admission ↗</a>';
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Student portal · Northstar</title><link rel="stylesheet" href="assets/university.css"><link rel="stylesheet" href="assets/theme.css"><script src="assets/theme.js" defer></script><script src="assets/razorpay-checkout.js" defer></script></head><body>
<?=siteHeader($spBrand,$spKind,'',$spButtons)?>
<?php if($page==='unavailable'): ?>
<main class="u-auth-wrap"><div class="u-card"><div class="u-eyebrow">WELCOME TO NORTHSTAR</div><h1>Portal not ready yet</h1>
<?php if($error): ?><div class="u-alert error" role="alert"><?=e($error)?></div><?php endif; ?>
<p>Your institute needs to finish the portal upgrade, or resolve a server issue. Contact the office; your existing records are not changed.</p>
<p><a class="u-btn solid" href="index.php?page=login">Back to sign in →</a></p>
</div></main>
<?php elseif($portalUser && !$student):
$appRef=null;$appStatus=null;
try{ $acc=one('SELECT id FROM applicant_accounts WHERE email=?',[$portalUser['email']]); if($acc){ $r=one('SELECT reference,status FROM admission_applications WHERE applicant_id=? ORDER BY id DESC LIMIT 1',[$acc['id']]); if($r){ $appRef=$r['reference']; $appStatus=$r['status']; } } }catch(Throwable $ignored){}
=======
if($student||$portalUser) {$spProfile=$student?['name'=>$student['name'],'role'=>'Student','url'=>'student.php']:['name'=>$portalUser['name'],'role'=>'Student','url'=>'student.php'];$spButtons.=siteProfileBox($spProfile).spForm('logout').'<button class="u-btn ghost" type="submit">Sign out ↗</button></form>';}
else $spButtons.='<a class="u-btn ghost" href="student.php?page=admissions">Apply for admission ↗</a><a class="u-btn ghost" href="index.php?page=login">Sign in ↗</a>';
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Student portal · Northstar</title><link rel="stylesheet" href="assets/university.css"><link rel="stylesheet" href="assets/theme.css"><script src="assets/theme.js" defer></script><script src="assets/razorpay-checkout.js" defer></script></head><body>
<?=siteHeader($spBrand,$spKind,'',$spButtons)?>
<?php if((!$student && !$portalUser) || $page==='unavailable'): ?>
<main class="u-auth-wrap"><div class="u-card"><div class="u-eyebrow">WELCOME TO NORTHSTAR</div><h1><?= $page==='unavailable'?'Portal not ready yet':'Your student space awaits' ?></h1>
<?php if($page==='unavailable'): ?><p>Your institute needs to finish the portal upgrade, or resolve a server issue. Contact the office; your existing records are not changed.</p>
<?php else: ?><p>Sign in with the verification code sent to your registered Gmail address.</p>
<?php if($flash): ?><div class="u-alert" role="status"><?=e($flash)?></div><?php endif; ?>
<?php if($error): ?><div class="u-alert error" role="alert"><?=e($error)?></div><?php endif; ?>
<?php if(isset($_SESSION['otp'])): ?><p class="u-small">Code sent to <?=e($_SESSION['otp']['email'])?>. It expires in five minutes.</p><?=spForm('verify_otp')?><div class="u-form"><label>Six-digit verification code<input name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" autocomplete="one-time-code" required class="u-code"></label><button class="u-btn solid">Verify &amp; sign in →</button></div></form><p><a href="student.php?page=login">Start over</a></p><?php else: ?><?=spForm('request_otp')?><div class="u-form"><label>Registered Gmail address<input type="email" name="email" value="<?=e(spPrefillEmail())?>" autocomplete="email" maxlength="200" required></label><button class="u-btn solid">Send verification code →</button></div></form><?php endif; ?>
<?php endif; ?></div></main>
<?php elseif($portalUser || $applicant):
$appRef=null;$appStatus=null;$openCourses=[];$selectedCourse=null;$myApplications=[];
try{ $acc=$applicant?:one('SELECT * FROM applicant_accounts WHERE email=? AND active=1',[$portalUser['email']]); if($acc){ $r=one('SELECT reference,status FROM admission_applications WHERE applicant_id=? ORDER BY id DESC LIMIT 1',[$acc['id']]); if($r){ $appRef=$r['reference']; $appStatus=$r['status']; } $myApplications=rows('SELECT * FROM admission_applications WHERE applicant_id=? ORDER BY id DESC LIMIT 50',[$acc['id']]); } $openCourses=publicCourses(); if(isset($_GET['course']))$selectedCourse=publicCourses(0,(int)$_GET['course'])[0]??null; }catch(Throwable $ignored){}
if(in_array($page,['admissions','courses','course','apply','applications','application'],true)){require __DIR__.'/student-admissions-view.php';return;}
>>>>>>> main
?>
<main class="u-page">
<nav class="u-tabs" aria-label="Student navigation"><a href="student.php" <?=$page==='dashboard'?'aria-current="page"':''?>>Overview</a><a href="student.php?page=admissions" <?=$page==='admissions'||$page==='courses'||$page==='course'||$page==='apply'?'aria-current="page"':''?>>Admissions</a><a href="student.php?page=applications" <?=$page==='applications'||$page==='application'?'aria-current="page"':''?>>My applications</a><a href="student.php?page=inquiries" <?=$page==='inquiries'?'aria-current="page"':''?>>Enquiries</a><a href="student.php?page=profile" <?=$page==='profile'?'aria-current="page"':''?>>My profile</a></nav>
<?php if($error): ?><div class="u-alert error" role="alert"><?=e($error)?></div><?php endif; ?><?php if($flash): ?><div class="u-alert" role="status"><?=e($flash)?></div><?php endif; ?>
<?php if($page==='profile'): ?><section class="u-card"><div class="u-eyebrow">YOUR DETAILS</div><h1>Keep your profile current</h1><p class="u-muted">Your verified email cannot be changed here. The office will use these details when reviewing an enquiry or application.</p><?=spForm('profile_update')?><div class="u-form"><label>Full name<input name="name" value="<?=e($portalUser['name'])?>" maxlength="120" required></label><label>Phone<input name="phone" value="<?=e($portalUser['phone'])?>" maxlength="30" required></label><label>Address<textarea name="address" rows="4" maxlength="300"><?=e($portalUser['address']??'')?></textarea></label><button class="u-btn solid">Save profile</button></div></form></section>
<?php elseif($page==='courses'): ?><div class="u-page-head"><div><div class="u-eyebrow">COURSE CATALOGUE</div><h1>Choose what comes next</h1><p>Explore currently open courses and move into the admissions portal when you are ready.</p></div></div><?php if(!$openCourses): ?><section class="u-card u-empty"><h2>No courses are open right now</h2><p>Check back soon or contact the institute for the next intake.</p></section><?php else: ?><div class="u-grid"><?php foreach(array_slice($openCourses,0,20) as $course): ?><section class="u-card"><div class="u-eyebrow"><?=e($course['institute_name'])?></div><h2><?=e($course['name'])?></h2><p><?=e($course['description'])?></p><p class="u-small"><?=e($course['duration'])?> · <?=e(spMoney((int)$course['fee_minor']))?> · closes <?=e($course['closes_on'])?></p><a class="u-btn solid" href="apply.php?course=<?=(int)$course['id']?>&page=course">View course and apply</a></section><?php endforeach; ?></div><?php endif; ?>
<?php elseif($page==='inquiries'): ?><section class="u-card"><div class="u-eyebrow">ADMISSIONS HELP</div><h1>Have a question?</h1><p>Use the admissions portal to review course details and submit an application, or contact the institute directly from its public contact page.</p><p><a class="u-btn solid" href="apply.php?page=help">Open admissions help</a> <a class="u-btn ghost" href="index.php?page=contact">Contact the institute</a></p></section>
<?php else: ?><div class="u-page-head"><div><div class="u-eyebrow">YOUR STUDENT SPACE</div><h1>Hello, <?=e(explode(' ',$portalUser['name'])[0])?>.</h1><p>Everything you need to explore courses, ask questions and manage your admission journey.</p></div></div><div class="u-grid"><section class="u-card"><div class="u-eyebrow">NEXT STEP</div><h2>Find your course</h2><p>See open courses, fees, eligibility and closing dates in one place.</p><a href="student.php?page=courses">Browse open courses →</a></section><section class="u-card"><div class="u-eyebrow">ADMISSION PORTAL</div><h2>Apply and track</h2><?php if($appRef): ?><p>Application <strong><?=e($appRef)?></strong> is <strong><?=e($appStatus)?></strong>.</p><?php else: ?><p>Start an application when you are ready. You can return to track its progress.</p><?php endif; ?><a href="apply.php?page=dashboard">Open admissions portal →</a></section><section class="u-card"><div class="u-eyebrow">YOUR PROFILE</div><h2><?=e($portalUser['name'])?></h2><p><?=e($portalUser['email'])?><br><?=e($portalUser['phone'])?></p><a href="student.php?page=profile">Update your details →</a></section><section class="u-card"><div class="u-eyebrow">NEED HELP?</div><h2>Ask the institute</h2><p>Get course and admissions guidance before you apply.</p><a href="student.php?page=inquiries">View enquiry options →</a></section></div><?php endif; ?>
</main>
<?php else:
$labels=['dashboard'=>'Overview','courses'=>'Open courses','applications'=>'My applications','payments'=>'My payments','documents'=>'My documents','profile'=>'My profile','academics'=>'Academic record','results'=>'My results','announcements'=>'Announcements','support'=>'Support'];
$total=(int)query('SELECT COALESCE(SUM(amount_minor),0) FROM payments WHERE student_id=?',[$student['id']])->fetchColumn();
$balance=(int)$student['fee_minor']-$total;
$docsCount=(int)query('SELECT COUNT(*) FROM documents WHERE student_id=?',[$student['id']])->fetchColumn();
?>
<main class="u-page"><nav class="u-tabs" aria-label="Student navigation"><?php foreach($labels as $key=>$label): ?><a href="student.php?page=<?=$key?>" <?=$page===$key?'aria-current="page"':''?>><?=e($label)?></a><?php endforeach; ?></nav>
<?php if($error): ?><div class="u-alert error" role="alert"><?=e($error)?></div><?php endif; ?><?php if($flash): ?><div class="u-alert" role="status"><?=e($flash)?></div><?php endif; ?>
<div class="u-page-head"><div class="u-eyebrow"><?=e($student['institute_name'])?></div><h1><?=e($labels[$page] ?? 'Page not found')?></h1><p><?=e(spNumber((int)$student['id']))?> · <?=e($student['course_name'])?> · <span class="u-pill">● Enrolled</span></p></div>
<?php if($page==='dashboard'): ?>
<section class="u-card"><div class="u-eyebrow">A LITTLE CLARITY FOR YOUR DAY</div><h2>Hello, <?=e(explode(' ',$student['name'])[0])?>.</h2><p>Your admission, payments and documents.<br>Everything you need to stay up to date.</p><a href="student.php?page=documents">Find your documents →</a></section>
<div class="u-stats"><?php foreach([['Agreed course fee',spMoney((int)$student['fee_minor'])],['Payments recorded',spMoney($total)],['Remaining balance',spMoney($balance)],['Available documents',(string)$docsCount]] as [$label,$value]): ?><section class="u-card u-stat"><span><?=e($label)?></span><strong><?=e($value)?></strong></section><?php endforeach; ?></div>
<div class="u-grid"><section class="u-card"><h2>Your admission</h2><dl class="u-dl"><div><dt>Student name</dt><dd><?=e($student['name'])?></dd></div><div><dt>Course</dt><dd><?=e($student['course_name'])?></dd></div><div><dt>Duration</dt><dd><?=e($student['duration'])?></dd></div><div><dt>Admitted on</dt><dd><?=e($student['admission_date'])?></dd></div><div><dt>Institute</dt><dd><?=e($student['institute_name'])?></dd></div></dl><a href="student.php?page=profile">View your full profile ↗</a></section><section class="u-card"><div class="u-eyebrow">HERE TO HELP</div><h2>A question about your records?</h2><p>Your institute office can help with payment corrections, contact details, and admission questions.</p><strong><?=e($student['institute_name'])?></strong><p><?=e($student['city'])?><br><?=e($student['institute_phone'])?></p><hr class="u-rule"><p class="u-small">Published attendance and batch information are in Academic record. Published exam results appear in My results. Use Support to ask the office a question.</p></section></div>
<?php elseif($page==='payments'):
$pn=max(1,(int)($_GET['p'] ?? 1));
$payments=rows('SELECT * FROM payments WHERE student_id=? ORDER BY paid_on DESC,id DESC LIMIT 21 OFFSET '.(($pn-1)*20),[$student['id']]);$more=count($payments)>20;$payments=array_slice($payments,0,20);
?>
<div class="u-stats"><?php foreach([['Course fee',spMoney((int)$student['fee_minor'])],['Total recorded',spMoney($total)],['Remaining balance',spMoney($balance)]] as [$label,$value]): ?><section class="u-card u-stat"><span><?=e($label)?></span><strong><?=e($value)?></strong></section><?php endforeach; ?></div>
<?php if(operationsReady()): $installments=studentInstallments((int)$student['id']); ?>
<section class="u-card"><h2>My installment schedule</h2><p class="u-small">Recorded payments cover earliest installments first. Only installments dated before today with unpaid amounts are overdue.</p><?php if(!$installments): ?><p class="u-small">Your institute has not set an installment schedule. Contact the office for due dates.</p><?php else: ?><div class="u-table-wrap"><table><thead><tr><th>Due date</th><th>Scheduled</th><th>Remaining</th><th>Status</th></tr></thead><tbody><?php foreach($installments as $i):?><tr><td><?=e($i['due_on'])?></td><td><?=e(spMoney((int)$i['amount_minor']))?></td><td><?=e(spMoney((int)$i['balance_minor']))?></td><td><?=e($i['status'])?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section><?php endif;?>
<?php if(function_exists('automationReady')&&automationReady()):$orders=onlineOrdersForStudent((int)$student['id']);$hold=$orders?one("SELECT * FROM online_orders WHERE student_id=? AND state IN ('Creating','Pending','Uncertain','Review') ORDER BY id DESC LIMIT 1",[$student['id']]):null;$gateway=null;$gatewayError=null;try{$gateway=gatewayAccount((int)$student['institute_id']);}catch(Throwable $e){$gatewayError=$e->getMessage();}
$focusOrder=null;if(isset($_GET['order'])){foreach($orders as $o)if((int)$o['id']===(int)$_GET['order'])$focusOrder=$o;}?>
<section class="u-card"><h2>Pay online</h2><?php if($gatewayError):?><p class="u-small"><?=e($gatewayError)?> Contact the office for payment options.</p><?php elseif($gateway['mode']==='test'):?><div class="u-alert">Test mode: no real money moves and test payments never credit your ledger. Use this only when the office asks you to test.</div><?php endif;?>
<?php if(!$gatewayError):?>
<?php if($hold):$caps=onlineCapturesForOrder((int)$hold['id']);?>
<p><strong>Order #<?=(int)$hold['id']?></strong> · <?=e(spMoney((int)$hold['amount_minor']))?> · <strong><?=e($hold['state'])?></strong><?php if($hold['provider_order']):?> · <?=e($hold['provider_order'])?><?php endif;?></p>
<?php if($hold['note']):?><p class="u-small"><?=e($hold['note'])?></p><?php endif;?>
<?php if($hold['state']==='Pending'&&$hold['provider_order']):?><script src="https://checkout.razorpay.com/v1/checkout.js" defer></script><button id="rzp-pay-button" class="u-btn solid" data-key="<?=e($gateway['key_id'])?>" data-order="<?=e($hold['provider_order'])?>" data-amount="<?=e((string)$hold['amount_minor'])?>" data-name="<?=e($student['institute_name'])?>" data-desc="<?=e('Course fee · Order #'.$hold['id'])?>" data-email="<?=e($student['email'])?>">Pay <?=e(spMoney((int)$hold['amount_minor']))?> securely →</button><p class="u-small">Complete payment in the secure Razorpay window, then use Check payment status. Do not create another order.</p><?php endif;?>
<?=spForm('online_sync')?><input type="hidden" name="order_id" value="<?=(int)$hold['id']?>"><button class="u-btn solid">Check payment status →</button></form>
<?php elseif($balance>0):?><?=spForm('online_order')?><div class="u-form"><label>Amount to pay online (up to <?=e(spMoney($balance))?>)<input name="amount" inputmode="decimal" maxlength="12" placeholder="5000.00" required></label><button class="u-btn solid">Create secure payment order →</button></div></form><p class="u-small">One order at a time. The office reconciles Uncertain orders; do not retry blindly.</p><?php else:?><p class="u-small">No outstanding balance. Contact the office if you expected to pay.</p><?php endif;?>
<?php if($orders):?><hr class="u-rule"><h3>Recent online orders</h3><div class="u-table-wrap"><table><thead><tr><th>Order</th><th>Amount</th><th>Mode</th><th>Status</th><th></th></tr></thead><tbody><?php foreach(array_slice($orders,0,5) as $o):?><tr><td>#<?=(int)$o['id']?><small><?=e($o['receipt'])?></small></td><td><?=e(spMoney((int)$o['amount_minor']))?></td><td><?=e($o['mode'])?></td><td><?=e($o['state'])?></td><td><a href="student.php?page=payments&order=<?=(int)$o['id']?>">View →</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<?php endif;?></section><?php endif;?>
<section class="u-card"><h2>Payment history</h2><p class="u-muted">Recorded payments and official receipts. Online test payments never appear here.</p><?php if(!$payments): ?><div class="u-empty"><h3>No payments recorded yet</h3><p>If you have already paid, contact the institute with your transaction details.</p></div><?php else: ?><div class="u-table-wrap"><table><thead><tr><th>Receipt</th><th>Date</th><th>Method / reference</th><th>Amount</th><th>PDF</th></tr></thead><tbody><?php foreach($payments as $p): $doc=one("SELECT id FROM documents WHERE student_id=? AND kind='payment' AND event_key=?",[$student['id'],'payment:'.$p['id']]); ?><tr><td>RCPT-<?=str_pad((string)$p['id'],7,'0',STR_PAD_LEFT)?></td><td><?=e($p['paid_on'])?></td><td><?=e($p['method'])?><small><?=e($p['reference'])?></small></td><td><?=e(spMoney((int)$p['amount_minor']))?></td><td><?php if($doc): ?><a href="student.php?document=<?=$doc['id']?>">Download ↓</a><?php else: ?>Not available<?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
<?php elseif($page==='documents'):
$pn=max(1,(int)($_GET['p'] ?? 1));$documents=rows('SELECT * FROM documents WHERE student_id=? ORDER BY id DESC LIMIT 21 OFFSET '.(($pn-1)*20),[$student['id']]);$more=count($documents)>20;$documents=array_slice($documents,0,20);
?>
<section class="u-card"><h2>Your important documents</h2><p class="u-muted">Admission letters and payment receipts, securely available only for your student record.</p><?php if(!$documents): ?><div class="u-empty"><h3>No documents available yet</h3><p>Ask the institute to generate your admission confirmation.</p></div><?php else: ?><div class="u-table-wrap"><table><thead><tr><th>Document</th><th>Created</th><th>Download</th></tr></thead><tbody><?php foreach($documents as $doc): ?><tr><td><strong><?=$doc['kind']==='payment'?'Payment receipt':'Admission confirmation'?></strong><small>Document #<?=$doc['id']?></small></td><td><?=e($doc['created_at'])?></td><td><a href="student.php?document=<?=$doc['id']?>">Download PDF ↓</a></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
<?php elseif(in_array($page,['results','announcements','support'],true)): require __DIR__.'/student-services.php'; ?>
<?php elseif($page==='academics'): require __DIR__.'/student-academics.php'; ?>
<?php elseif($page==='profile'): ?>
<section class="u-card"><h2>My student record</h2><p class="u-small">Your details are maintained by the institute. Contact the office for changes; you cannot edit admissions or payment records here.</p><dl class="u-dl"><?php foreach(['Student ID'=>spNumber((int)$student['id']),'Full name'=>$student['name'],'Registered email'=>$student['email'],'Phone'=>$student['phone'],'Course'=>$student['course_name'],'Duration'=>$student['duration'],'Admission date'=>$student['admission_date'],'Institute'=>$student['institute_name'],'City'=>$student['city'],'Office phone'=>$student['institute_phone']] as $label=>$value): ?><div><dt><?=e($label)?></dt><dd><?=e($value)?></dd></div><?php endforeach; ?></dl></section>
<?php else: ?><section class="u-card u-empty"><h2>Page not found</h2><a href="student.php">Return to your overview</a></section><?php endif; ?>
<?php if(in_array($page,['payments','documents'],true)): ?><div class="u-pagination"><span>Page <?=$pn?></span><div><?php if($pn>1): ?><a href="student.php?page=<?=e($page)?>&p=<?=$pn-1?>">← Previous</a><?php endif; ?><?php if($more): ?><a href="student.php?page=<?=e($page)?>&p=<?=$pn+1?>">Next →</a><?php endif; ?></div></div><?php endif; ?>
<p class="u-footnote">Balances show the admission fee minus recorded payments. Installment due dates appear only when the institute creates a schedule. Receipt amounts are saved snapshots and may differ from today's balance.</p>
</main><?php endif; ?><p class="u-footnote"><?=siteBackLink()?></p><?=siteFooter($spBrand,$spKind,$spCity,$spAddr,$spPhone)?></body></html>
