<?php
declare(strict_types=1);
require_once __DIR__.'/site-chrome.php';
function spMoney(int $n): string { return '₹'.number_format($n/100,2); }
function spNumber(int $n): string { return 'ST-'.str_pad((string)$n,5,'0',STR_PAD_LEFT); }
function spForm(string $action): string { return '<form method="post">'.csrf().'<input type="hidden" name="action" value="'.e($action).'">'; }
function spPrefillEmail(): string { $v=is_string($_GET['email'] ?? null)?trim(substr($_GET['email'],0,200)):''; return filter_var($v,FILTER_VALIDATE_EMAIL)?$v:''; }
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Student portal · Northstar</title><link rel="stylesheet" href="assets/student.css"><link rel="stylesheet" href="assets/university.css"><link rel="stylesheet" href="assets/theme.css"><script src="assets/theme.js" defer></script><script src="assets/razorpay-checkout.js" defer></script></head><body>
<header class="sp-top"><?php [$spBrand,$spKind]=siteBrand(); ?><a class="u-brand" href="<?=e(siteHomeUrl())?>" title="Back to the university website"><span class="u-brand-mark">+</span><span><?=e($spBrand)?><em><?=e($spKind)?></em></span></a><div class="sp-top-right"><?=siteBackLink('sp-back')?><button class="theme-toggle" data-theme-toggle type="button" aria-label="Toggle dark mode" title="Toggle dark mode"><span aria-hidden="true">🌙</span></button><span class="sp-label">STUDENT WORKSPACE</span><?php if($student||$portalUser): ?><?=spForm('logout')?><button class="sp-text-button">Sign out ↗</button></form><?php else: ?><a href="student.php?page=register">Create account ↗</a> · <a href="apply.php">Apply for admission ↗</a> · <a href="index.php">Staff login ↗</a><?php endif; ?></div></header>
<?php if((!$student && !$portalUser) || $page==='unavailable'): ?>
<main class="sp-login"><section class="sp-login-intro"><div class="sp-eyebrow">YOUR NEXT CHAPTER</div><h1>Learning is a journey.<br>Your details,<br>all in one place.</h1><p>Check your admission, keep track of payments, and find your important documents—without a trip to the office.</p><div class="sp-intro-note">✦ <span>Made for your student life.</span></div></section><section class="sp-login-card"><div class="sp-eyebrow">WELCOME TO NORTHSTAR</div><h2><?= $page==='unavailable'?'Portal not ready yet':'Your student space awaits' ?></h2>
<?php if($error): ?><div class="sp-alert error" role="alert"><?=e($error)?></div><?php endif; ?>
<?php if($page==='unavailable'): ?><p>Your institute needs to finish the portal upgrade, or resolve a server issue. Contact the office; your existing records are not changed.</p>
<?php elseif($page==='register'): ?><p>Create your free student account. Verify your email, then apply for admission — after the office approves you, this same account opens your full portal.</p>
<?php if($flash): ?><div class="sp-alert" role="status"><?=e($flash)?></div><?php endif; ?>
<?php if(!studentUsersReady()): ?><p>Registration is not ready yet. The institute must run the upgrade first. Admitted students can still sign in below.</p><p><a class="sp-link" href="student.php">Back to sign-in →</a></p>
<?php else: ?>
<?php if(isset($_SESSION['suid_pending'])): ?><p class="sp-small">Code sent to <?=e($_SESSION['suid_pending']['email'])?>. Use this browser within five minutes. Already registered with this email? The same code signs you in.</p><?=spForm('register_verify')?><label>Six-digit verification code<input name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" autocomplete="one-time-code" required class="sp-code"></label><button class="sp-button">Verify & continue →</button></form><div class="sp-rule"></div><?php endif; ?>
<?=spForm('register_request')?><label>Full name<input name="name" maxlength="120" value="<?=e($_SESSION['suid_pending']['name'] ?? '')?>" autocomplete="name" required></label><label>Email address<input type="email" name="email" maxlength="200" value="<?=e($_SESSION['suid_pending']['email'] ?? '')?>" autocomplete="email" required></label><label>Contact phone<input name="phone" maxlength="30" value="<?=e($_SESSION['suid_pending']['phone'] ?? '')?>" autocomplete="tel" required></label><div class="sp-trap" aria-hidden="true"><label>Leave this blank<input name="website" tabindex="-1" autocomplete="off"></label></div><button class="sp-button">Send verification code →</button></form><p class="sp-small">Use your own email address. Wait 60 seconds before resending. <a href="student.php">Already admitted? Sign in →</a></p>
<?php endif; ?>
<?php else: ?><p>Sign in with a code sent to your registered student email.</p>
<?php if($flash): ?><div class="sp-alert" role="status"><?=e($flash)?></div><?php endif; ?>
<?php if(($config['environment'] ?? '')==='local' && ($config['mail']['transport'] ?? '')==='log'): ?><div class="sp-alert">Local demo: email is captured privately in storage/mail/. No real email is sent.</div><?php endif; ?>
<?php if(isset($_SESSION['otp'])): ?><p class="sp-small">Code requested for <?=e($_SESSION['otp']['email'])?>. Use this browser within five minutes.</p><?=spForm('verify_otp')?><label>Six-digit sign-in code<input name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" autocomplete="one-time-code" required class="sp-code"></label><button class="sp-button">Verify & sign in →</button></form><div class="sp-rule"></div><?php endif; ?>
<?=spForm('request_otp')?><label>Registered student email<input type="email" name="email" value="<?=e($_SESSION['otp']['email'] ?? spPrefillEmail())?>" autocomplete="email" maxlength="200" required></label><button class="sp-button"><?=isset($_SESSION['otp'])?'Send a new code':'Send sign-in code'?> →</button></form><p class="sp-small">Ask your institute to enable your portal first. Only admitted students with enabled access can sign in. Wait 60 seconds before resending.</p><div class="sp-rule"></div><h3>New student?</h3><p>Create your free account with email verification, then apply for admission. After approval, the same account opens your full portal.</p><p><a class="sp-button" href="student.php?page=register">Create student account →</a></p>
<?php endif; ?></section></main>
<?php elseif($portalUser && !$student):
$appRef=null;$appStatus=null;
try{ $acc=one('SELECT id FROM applicant_accounts WHERE email=?',[$portalUser['email']]); if($acc){ $r=one('SELECT reference,status FROM admission_applications WHERE applicant_id=? ORDER BY id DESC LIMIT 1',[$acc['id']]); if($r){ $appRef=$r['reference']; $appStatus=$r['status']; } } }catch(Throwable $ignored){}
?>
<div class="sp-workspace"><main class="sp-content">
<?php if($error): ?><div class="sp-alert error" role="alert"><?=e($error)?></div><?php endif; ?><?php if($flash): ?><div class="sp-alert" role="status"><?=e($flash)?></div><?php endif; ?>
<section class="sp-card"><div class="sp-eyebrow">STUDENT ACCOUNT</div><h1>Hello, <?=e(explode(' ',$portalUser['name'])[0])?>.</h1><p>Verified email: <strong><?=e($portalUser['email'])?></strong></p>
<?php if($appRef): ?><p>Your latest application <strong><?=e($appRef)?></strong> is: <strong><?=e($appStatus)?></strong>.</p><?php if($appStatus==='Admitted'): ?><p>Your admission is approved. If the office has enabled your portal, <a href="student.php">refresh this page</a> to open your full student portal.</p><?php else: ?><p><a class="sp-button" href="apply.php?page=dashboard">Track your application &rarr;</a></p><?php endif; ?>
<?php else: ?><p>You have not applied for admission yet. Your full portal &mdash; fees, payments, documents and results &mdash; opens after the office approves your application.</p><p><a class="sp-button" href="apply.php">Apply for admission &rarr;</a></p><?php endif; ?>
<p class="sp-small">If the office just enabled your access, refresh this page. For help, contact your institute office.</p></section>
</main></div>
<?php else:
$labels=['dashboard'=>'Overview','payments'=>'My payments','documents'=>'My documents','profile'=>'My profile','academics'=>'Academic record','results'=>'My results','announcements'=>'Announcements','support'=>'Support'];
$total=(int)query('SELECT COALESCE(SUM(amount_minor),0) FROM payments WHERE student_id=?',[$student['id']])->fetchColumn();
$balance=(int)$student['fee_minor']-$total;
$docsCount=(int)query('SELECT COUNT(*) FROM documents WHERE student_id=?',[$student['id']])->fetchColumn();
?>
<div class="sp-workspace"><nav class="sp-nav" aria-label="Student navigation"><?php foreach($labels as $key=>$label): ?><a href="student.php?page=<?=$key?>" <?=$page===$key?'aria-current="page"':''?>><?=e($label)?></a><?php endforeach; ?></nav><main class="sp-content">
<?php if($error): ?><div class="sp-alert error" role="alert"><?=e($error)?></div><?php endif; ?><?php if($flash): ?><div class="sp-alert" role="status"><?=e($flash)?></div><?php endif; ?>
<div class="sp-heading"><div><div class="sp-eyebrow"><?=e($student['institute_name'])?></div><h1><?=e($labels[$page] ?? 'Page not found')?></h1><p><?=e(spNumber((int)$student['id']))?> · <?=e($student['course_name'])?></p></div><span class="sp-status">● Enrolled</span></div>
<?php if($page==='dashboard'): ?>
<section class="sp-welcome"><div><span class="sp-eyebrow">A LITTLE CLARITY FOR YOUR DAY</span><h2>Hello, <?=e(explode(' ',$student['name'])[0])?>.</h2><p>Your admission, payments and documents.<br>Everything you need to stay up to date.</p><a href="student.php?page=documents">Find your documents →</a></div><span class="sp-star" aria-hidden="true">✦</span></section>
<div class="sp-stats"><?php foreach([['Agreed course fee',spMoney((int)$student['fee_minor'])],['Payments recorded',spMoney($total)],['Remaining balance',spMoney($balance)],['Available documents',(string)$docsCount]] as [$label,$value]): ?><section class="sp-card sp-stat"><span><?=e($label)?></span><strong><?=e($value)?></strong></section><?php endforeach; ?></div>
<div class="sp-columns"><section class="sp-card"><h2>Your admission</h2><dl><div><dt>Student name</dt><dd><?=e($student['name'])?></dd></div><div><dt>Course</dt><dd><?=e($student['course_name'])?></dd></div><div><dt>Duration</dt><dd><?=e($student['duration'])?></dd></div><div><dt>Admitted on</dt><dd><?=e($student['admission_date'])?></dd></div><div><dt>Institute</dt><dd><?=e($student['institute_name'])?></dd></div></dl><a class="sp-link" href="student.php?page=profile">View your full profile ↗</a></section><section class="sp-card sp-help"><div class="sp-eyebrow">HERE TO HELP</div><h2>A question about your records?</h2><p>Your institute office can help with payment corrections, contact details, and admission questions.</p><strong><?=e($student['institute_name'])?></strong><p><?=e($student['city'])?><br><?=e($student['institute_phone'])?></p><div class="sp-rule"></div><p class="sp-small">Published attendance and batch information are in Academic record. Published exam results appear in My results. Use Support to ask the office a question.</p></section></div>
<?php elseif($page==='payments'):
$pn=max(1,(int)($_GET['p'] ?? 1));
$payments=rows('SELECT * FROM payments WHERE student_id=? ORDER BY paid_on DESC,id DESC LIMIT 21 OFFSET '.(($pn-1)*20),[$student['id']]);$more=count($payments)>20;$payments=array_slice($payments,0,20);
?>
<div class="sp-stats three"><?php foreach([['Course fee',spMoney((int)$student['fee_minor'])],['Total recorded',spMoney($total)],['Remaining balance',spMoney($balance)]] as [$label,$value]): ?><section class="sp-card sp-stat"><span><?=e($label)?></span><strong><?=e($value)?></strong></section><?php endforeach; ?></div>
<?php if(operationsReady()): $installments=studentInstallments((int)$student['id']); ?>
<section class="sp-card"><h2>My installment schedule</h2><p class="sp-small">Recorded payments cover earliest installments first. Only installments dated before today with unpaid amounts are overdue.</p><?php if(!$installments): ?><p class="sp-small">Your institute has not set an installment schedule. Contact the office for due dates.</p><?php else: ?><div class="sp-table-wrap"><table><thead><tr><th>Due date</th><th>Scheduled</th><th>Remaining</th><th>Status</th></tr></thead><tbody><?php foreach($installments as $i):?><tr><td><?=e($i['due_on'])?></td><td><?=e(spMoney((int)$i['amount_minor']))?></td><td><?=e(spMoney((int)$i['balance_minor']))?></td><td><?=e($i['status'])?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section><div class="sp-rule"></div><?php endif;?>
<?php if(function_exists('automationReady')&&automationReady()):$orders=onlineOrdersForStudent((int)$student['id']);$hold=$orders?one("SELECT * FROM online_orders WHERE student_id=? AND state IN ('Creating','Pending','Uncertain','Review') ORDER BY id DESC LIMIT 1",[$student['id']]):null;$gateway=null;$gatewayError=null;try{$gateway=gatewayAccount((int)$student['institute_id']);}catch(Throwable $e){$gatewayError=$e->getMessage();}
$focusOrder=null;if(isset($_GET['order'])){foreach($orders as $o)if((int)$o['id']===(int)$_GET['order'])$focusOrder=$o;}?>
<section class="sp-card"><h2>Pay online</h2><?php if($gatewayError):?><p class="sp-small"><?=e($gatewayError)?> Contact the office for payment options.</p><?php elseif($gateway['mode']==='test'):?><div class="sp-alert">Test mode: no real money moves and test payments never credit your ledger. Use this only when the office asks you to test.</div><?php endif;?>
<?php if(!$gatewayError):?>
<?php if($hold):$caps=onlineCapturesForOrder((int)$hold['id']);?>
<p><strong>Order #<?=(int)$hold['id']?></strong> · <?=e(spMoney((int)$hold['amount_minor']))?> · <strong><?=e($hold['state'])?></strong><?php if($hold['provider_order']):?> · <?=e($hold['provider_order'])?><?php endif;?></p>
<?php if($hold['note']):?><p class="sp-small"><?=e($hold['note'])?></p><?php endif;?>
<?php if($hold['state']==='Pending'&&$hold['provider_order']):?><script src="https://checkout.razorpay.com/v1/checkout.js" defer></script><button id="rzp-pay-button" class="sp-button" data-key="<?=e($gateway['key_id'])?>" data-order="<?=e($hold['provider_order'])?>" data-amount="<?=e((string)$hold['amount_minor'])?>" data-name="<?=e($student['institute_name'])?>" data-desc="<?=e('Course fee · Order #'.$hold['id'])?>" data-email="<?=e($student['email'])?>">Pay <?=e(spMoney((int)$hold['amount_minor']))?> securely →</button><p class="sp-small">Complete payment in the secure Razorpay window, then use Check payment status. Do not create another order.</p><?php endif;?>
<?=spForm('online_sync')?><input type="hidden" name="order_id" value="<?=(int)$hold['id']?>"><button class="sp-button">Check payment status →</button></form>
<?php elseif($balance>0):?><?=spForm('online_order')?><label>Amount to pay online (up to <?=e(spMoney($balance))?>)<input name="amount" inputmode="decimal" maxlength="12" placeholder="5000.00" required></label><button class="sp-button">Create secure payment order →</button></form><p class="sp-small">One order at a time. The office reconciles Uncertain orders; do not retry blindly.</p><?php else:?><p class="sp-small">No outstanding balance. Contact the office if you expected to pay.</p><?php endif;?>
<?php if($orders):?><div class="sp-rule"></div><h3>Recent online orders</h3><div class="sp-table-wrap"><table><thead><tr><th>Order</th><th>Amount</th><th>Mode</th><th>Status</th><th></th></tr></thead><tbody><?php foreach(array_slice($orders,0,5) as $o):?><tr><td>#<?=(int)$o['id']?><small><?=e($o['receipt'])?></small></td><td><?=e(spMoney((int)$o['amount_minor']))?></td><td><?=e($o['mode'])?></td><td><?=e($o['state'])?></td><td><a href="student.php?page=payments&order=<?=(int)$o['id']?>">View →</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<?php endif;?></section><div class="sp-rule"></div><?php endif;?>
<section class="sp-card sp-table-card"><div class="sp-table-head"><h2>Payment history</h2><p>Recorded payments and official receipts. Online test payments never appear here.</p></div><?php if(!$payments): ?><div class="sp-empty"><h3>No payments recorded yet</h3><p>If you have already paid, contact the institute with your transaction details.</p></div><?php else: ?><div class="sp-table-wrap"><table><thead><tr><th>Receipt</th><th>Date</th><th>Method / reference</th><th>Amount</th><th>PDF</th></tr></thead><tbody><?php foreach($payments as $p): $doc=one("SELECT id FROM documents WHERE student_id=? AND kind='payment' AND event_key=?",[$student['id'],'payment:'.$p['id']]); ?><tr><td>RCPT-<?=str_pad((string)$p['id'],7,'0',STR_PAD_LEFT)?></td><td><?=e($p['paid_on'])?></td><td><?=e($p['method'])?><small><?=e($p['reference'])?></small></td><td><?=e(spMoney((int)$p['amount_minor']))?></td><td><?php if($doc): ?><a href="student.php?document=<?=$doc['id']?>">Download ↓</a><?php else: ?>Not available<?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
<?php elseif($page==='documents'):
$pn=max(1,(int)($_GET['p'] ?? 1));$documents=rows('SELECT * FROM documents WHERE student_id=? ORDER BY id DESC LIMIT 21 OFFSET '.(($pn-1)*20),[$student['id']]);$more=count($documents)>20;$documents=array_slice($documents,0,20);
?>
<section class="sp-card sp-table-card"><div class="sp-table-head"><h2>Your important documents</h2><p>Admission letters and payment receipts, securely available only for your student record.</p></div><?php if(!$documents): ?><div class="sp-empty"><h3>No documents available yet</h3><p>Ask the institute to generate your admission confirmation.</p></div><?php else: ?><div class="sp-table-wrap"><table><thead><tr><th>Document</th><th>Created</th><th>Download</th></tr></thead><tbody><?php foreach($documents as $doc): ?><tr><td><strong><?=$doc['kind']==='payment'?'Payment receipt':'Admission confirmation'?></strong><small>Document #<?=$doc['id']?></small></td><td><?=e($doc['created_at'])?></td><td><a href="student.php?document=<?=$doc['id']?>">Download PDF ↓</a></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
<?php elseif(in_array($page,['results','announcements','support'],true)): require __DIR__.'/student-services.php'; ?>
<?php elseif($page==='academics'): require __DIR__.'/student-academics.php'; ?>
<?php elseif($page==='profile'): ?>
<section class="sp-card"><h2>My student record</h2><p class="sp-small">Your details are maintained by the institute. Contact the office for changes; you cannot edit admissions or payment records here.</p><dl><?php foreach(['Student ID'=>spNumber((int)$student['id']),'Full name'=>$student['name'],'Registered email'=>$student['email'],'Phone'=>$student['phone'],'Course'=>$student['course_name'],'Duration'=>$student['duration'],'Admission date'=>$student['admission_date'],'Institute'=>$student['institute_name'],'City'=>$student['city'],'Office phone'=>$student['institute_phone']] as $label=>$value): ?><div><dt><?=e($label)?></dt><dd><?=e($value)?></dd></div><?php endforeach; ?></dl></section>
<?php else: ?><section class="sp-card sp-empty"><h2>Page not found</h2><a href="student.php">Return to your overview</a></section><?php endif; ?>
<?php if(in_array($page,['payments','documents'],true)): ?><div class="sp-pagination"><span>Page <?=$pn?></span><div><?php if($pn>1): ?><a href="student.php?page=<?=e($page)?>&p=<?=$pn-1?>">← Previous</a><?php endif; ?><?php if($more): ?><a href="student.php?page=<?=e($page)?>&p=<?=$pn+1?>">Next →</a><?php endif; ?></div></div></section><?php endif; ?>
<p class="sp-footnote">Balances show the admission fee minus recorded payments. Installment due dates appear only when the institute creates a schedule. Receipt amounts are saved snapshots and may differ from today's balance.</p>
</main></div><?php endif; ?><footer class="sp-footer">northstar. <span>Your institute, a little closer.</span> <?=siteBackLink()?></footer></body></html>
